### ISSUE TITLE
Successful build without binary? [CentOS 7]

### ISSUE THREAD

**Issue by krizajb** [rabbitvcs/rabbitvcs#107]
Following your manual steps with slight modification of setup.py on CentOS 7 I ended up with successful build (no errors) but without any executable. Any ideas?

setup.py modification:
I couldn't find gtk-update-icon-cache-3.0 executable on my distro so I just changed the executable name with gtk-update-icon-cache in the icon cache deletion and recreation section.

Installed packages (devel included):
- pygtk2 (2.24.0-9)
- python-configobj (4.7.2-7)
- pygobject2 (2.28.6-11)
- pygobject3 (3.8.2-6)
- python-simplejson (3.3.3-1)
- pysvn (1.7.6-10)
- subversion-python (1.8.11-1)
- subversion (1.8.11-1)

See also more detailed description [here](http://unix.stackexchange.com/questions/215856/how-to-install-rabbitvcs-on-centos-7-nautlius-3).

**Comment by adamplumb** [comment]
Thanks, this is finally fixed on master.
