### ISSUE TITLE
Date format in log history

### ISSUE THREAD

**Issue by martin-luy** [rabbitvcs/rabbitvcs#116]
Hi,

The log history shows mixed date formats:
![log-history](https://cloud.githubusercontent.com/assets/4472985/9975535/5035fe76-5ebf-11e5-85d6-5a13eba885cf.png)

How can I configure RabbitVCS to show the complete timestamp for all revisions? E.g. "Sep 11 2015 09:55:23" or "2015-09-11 09:55:23".

Didn't find that in the settings and in the wiki etc.

RabbitVCS 0.16.0
SVN 1.8.8
GNOME nautilus 3.10.1
ubuntu 14.04 LTS

BR
Martin

**Comment by adamplumb** [comment]
Looks like issue #156 is a duplicate of this one.

**Comment by martin-luy** [comment]
correct
