### ISSUE TITLE
doesn't work with empty emails

### ISSUE THREAD

**Issue by simonzack** [rabbitvcs/rabbitvcs#121]
When `<>` is the email (empty email), the email is committed as `<`.

**Comment by monnerat** [comment]
This is a dulwich library bug. I submitted a PR for it (https://github.com/dulwich/dulwich/pull/722) but it won't be fixed before at least dulwich 0.19.14.
I do not plan to implement a workaround in RabbitVCS itself.

**Comment by monnerat** [comment]
A fix has been committed to dulwich. This means the problem will disappear if you use a snapshot of current dulwich master.
Thanks for reporting. Closing this issue.
