### ISSUE TITLE
Is this project alive? Website shows default Nginx installation, no update for months

### ISSUE THREAD

**Issue by timofonic** [rabbitvcs/rabbitvcs#129]
Hello.

Is this project alive?
- A configuration error makes the official website not to appear if using www.: There's no content, just the default page when installing Nginx under Fedora. It works correctly by entering http://rabbitvcs.org
- There hasn't been source code commits since months.
  "It's dead, Jim"?

Other fork provides updated code:

https://github.com/Fordi/rabbitvcs

Kind regards.

**Comment by adamplumb** [comment]
Maybe not quite dead, but not fully alive either.  I fixed the website and am making some bugfixes.  We'll see.
