### ISSUE TITLE
http://www.rabbitvcs.org serves a default nginx page

### ISSUE THREAD

**Issue by dregad** [rabbitvcs/rabbitvcs#131]
I got this URL from the context-menu / about

Shouldn't it redirect to http://rabbitvcs.org ?

RabbitVCS 0.16.0 on Ubuntu 15.10

**Comment by dregad** [comment]
https://github.com/rabbitvcs/rabbitvcs/blob/master/README.md also points to http://www.rabbitvcs.org

**Comment by dregad** [comment]
Just noticed this was also reported in #129.

**Comment by kwill** [comment]
As mentioned in #129, http://rabbitvcs.org works (but obviously www should be fixed).

**Comment by adamplumb** [comment]
Thanks should be fixed now
