### ISSUE TITLE
git stage menu has no effect in 0.16-1~precise

### ISSUE THREAD

**Issue by gaschler** [rabbitvcs/rabbitvcs#14]
I'm using the ppa version rabbitvcs-nautilus3 0.16-1~precise 64bit

Reproduce:
1. create a new file "test" in a git indexed folder 
2. right-click in nautilus on the file -> git -> stage

Actual behavoir:
nothing, no logs

Expected behavoir:
same as 
git stage test

**Comment by florian-rabis** [comment]
Please do the same in the unstage.py-class. The show_ignored attribute is also missing there.
