### ISSUE TITLE
Feature request: svn changelist support

### ISSUE THREAD

**Issue by eshulman-degiro** [rabbitvcs/rabbitvcs#146]
Hi, nice project! But one thing that is really useful is changelist management.
At the very least, **changes.py** should be able to group by CL.
Hope this can be added in the future ^_^

**Comment by adamplumb** [comment]
I don't really have any experience with svn changelists.  You're welcome to put some work into supporting it  though.  Let me know if I can help with any kind of guidance.

**Comment by srMarquinho** [comment]
I'd love to see that feature. It's quite handy once you get used to it.
For [reference only](https://tortoisesvn.net/docs/release/TortoiseSVN_en/tsvn-dug-changelists.html)!
