### ISSUE TITLE
rabbitvcs.org registration does not work anymore

### ISSUE THREAD

**Issue by jesponde** [rabbitvcs/rabbitvcs#147]
Hi,
I would like to update FAQ in wiki pages to write down a workaround for people who want to use rabbitvcs with a git server that need authentication.
To do that, it looks like I need to register to the website. But I never received any email as said by the registration page.
Does someone have any information about that?

**Comment by kwill** [comment]
That sounds helpful! For now, you could post it here, or as a Q&A on Super User or Ask Ubuntu. If you post it here, please clearly attribute it with an appropriate Creative Commons license [1] so it can be include on the wiki later.

[1] https://creativecommons.org/licenses/by-sa/3.0/ is the one they currently use on the wiki.

**Comment by adamplumb** [comment]
I'm going to try to move the wiki to github.
