### ISSUE TITLE
Support for SpaceFM

### ISSUE THREAD

**Issue by kaqqao** [rabbitvcs/rabbitvcs#15]
SpaceFM is the default in many smaller distributions. Its menu is really easy to extend (doable from the context menu itself) and the author is very approachable.

**Comment by Xylemon** [comment]
SpaceFM is not abandoned, it was only on hiatus and is actually back in development.

**Comment by Xylemon** [comment]
Thanks.

**Comment by adamplumb** [comment]
I know this is quite late but I'm trying to catch up.  We don't really have much in the way of documentation for adding new integrations but there are a couple ways to integrate RabbitVCS.

1) Add a context menu.  Mostly you should just need to tell it which menu items to show and RabbitVCS should do the rest, determining which to make visible or not.  See the Nautilus, Thunar, and Caja clients for more info.

2) Show status icons.  This is very much dependent on how SpaceFM works.  If there is icon support then we should be able to work with it.  Check out the Nautilus-3.0 client for more, specifically the update_file_info method.

3) Update file property dialog.  I'm not sure if SpaceFM supports this, but we do this for nautilus and thunar.

I'm happy to answer any questions if you're interested in moving forward with this.

**Comment by kaqqao** [comment]
Sadly, I no longer have a Linux machine to work on so, for the foreseeable future at least, I won't be able to help with this.

**Comment by adamplumb** [comment]
OK no worries I'll close this out.
