### ISSUE TITLE
ubuntu 16.04 xenial xerus  + apt-get update error.

### ISSUE THREAD

**Issue by ssinfod** [rabbitvcs/rabbitvcs#152]
Hello, I install rabbitvcs on ubuntu 16.04 and it works fine.

However, now I have the following error when I run: 
sudo apt-get update

E: Failed to fetch http://ppa.launchpad.net/rabbitvcs/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/rabbitvcs/ppa/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

Any idea what is wrong ?

**Comment by RobbiNespu** [comment]
@ssinfod  Because the PPA dont have package for ubuntu 16.04 LTS (Xenial) ye.
Check : http://ppa.launchpad.net/rabbitvcs/ppa/ubuntu/dists/ :-1: 

Btw, I'm waiting too for **rabbitvcs-nautilus3 **for ubuntu 16.04

**Comment by syntaxerror** [comment]
deb http://ppa.launchpad.net/rabbitvcs/ppa/ubuntu trusty main
- works fine

**Comment by bromount** [comment]
Team,
Any update on when you will add dist xenial in PPA?

**Comment by adamplumb** [comment]
The person who kept our PPAs updated, Jason, has stepped down.  So I don't know what will happen going forward.
