### ISSUE TITLE
Always show complete date time in current locale

### ISSUE THREAD

**Issue by Mondane** [rabbitvcs/rabbitvcs#153]
As it is now, the interface 'breaks' the display of timestamps according to these rules found in https://github.com/rabbitvcs/rabbitvcs/blob/master/rabbitvcs/util/helper.py#L114

This format confuses me, I like to have it always shown as a full date/time and preferably in my own locale. Could this be added (as a config setting)?

As a  workaround, I've changed the function locally (/usr/lib/python2.7/dist-packages/rabbitvcs/util/helper.py) to:

```
def format_datetime(dt, format=None):
    if format:
        enc = locale.getpreferredencoding(False)
        if enc is None or len(enc) == 0:
            enc = "UTF8"
        return dt.strftime(format).decode(enc)

    returner = dt.strftime(LOCAL_DATETIME_FORMAT)
    enc = locale.getpreferredencoding(False)
    if enc is None or len(enc) == 0:
        enc = "UTF8"
    return returner.decode(enc)
```

**Comment by adamplumb** [comment]
Someone in issue #156 requested something similar.  I think it makes sense to be able to configure this.  I personally like having the time formatted the way it is, but I can see the benefit of doing it your way too.  So something where the settings dialog can force a particular datetime format would be nice.  Feel free to submit a PR.

**Comment by monnerat** [comment]
Commit 507def5 introduces date/time format settings. You should now be able to find a configurable format that better suits your requirements. If the problem persists, please repoen this issue.
