### ISSUE TITLE
Date / time of revisions in log

### ISSUE THREAD

**Issue by vo-borodin** [rabbitvcs/rabbitvcs#156]
When I open log in RabbitVCS SVN by "Show Log", the date / time of revisions is shown in format "<Month (short form)> <day of month> <full year>" (e. g. "Aug. 16 2015", in Russian localization it is "авг. 16 2015"). It is uncomfortably, I would like to see date / time in accustomed format "dd.MM.yyyy HH:mm:SS" (e.g. "16.08.2015 18:35:23"). Is it possible?

**Comment by adamplumb** [comment]
This seems doable if we add some configuration to the settings dialog to set the time format and apply that to the log dialog.  Feel free to submit a pull request.

**Comment by monnerat** [comment]
Commit 507def5 introduces date/time format settings. You should now be able to find a configurable format that better suits your requirements. If the problem persists, please repoen this issue.
