### ISSUE TITLE
MacOS build of rabbitvcs-cli

### ISSUE THREAD

**Issue by ddalcu** [rabbitvcs/rabbitvcs#160]
Hello,

The wiki contains an entry about OSX: http://wiki.rabbitvcs.org/wiki/development/osx

But:

the page links to some old page with a build that no longer exists.
the developer instructions seem outdated and mention /Developer locations that are no longer valid 

Would it be possible to update the wiki with a link to an updated rabbitvcs-cli binary for MacOS ?

Thank you

**Comment by adamplumb** [comment]
It would be nice to have an OSX build but that was a long time ago and the wiki is out of date.  It should be possible to package RabbitVCS for OSX but someone would need to do the work to make it happen.

If you follow the rest of the wiki to install it yourself you might make some progress.  Check out clients/osx_finder for what exists.  Maybe it will still work?  Good luck!
