### ISSUE TITLE
Debian user reported accidental removal of home directory

### ISSUE THREAD

**Issue by MartinBorg** [rabbitvcs/rabbitvcs#161]
I found this bug report in Debian:
https://bugs.debian.org/817231
The user mentions a similar report for Ubuntu:
http://askubuntu.com/questions/473433/rabbitsvn-deleted-all-my-folders
I do not use RabbitVCS myself, so I can't comment on this.
My colleagues did use it on Debian and never had any severe problem with it, however.
Thanks anyway for checking!

**Comment by bedorlan** [comment]
+1

Steps:
0. debian testing, rabbitvcs-nautilus
1. Repository Browser
2. Right-click in a single file and Export
3. Select a folder
4. Click Ok

The folder gets overwrited and become a file, with the contents of the file selected for export.

**Comment by detly** [comment]
Seems like #127 in the case that the export directory is home directory.

**Comment by MartinBorg** [comment]
@detly : Yes, it looks like the same issue, so this one can probably just closed as duplicate.
