### ISSUE TITLE
Ubuntu 16.04 support

### ISSUE THREAD

**Issue by rnyberg** [rabbitvcs/rabbitvcs#162]
I tested using rabbitvcs-core and rabbitvcs-nautilus3 from trusty ppa since they worked for me on 14.04, but on 16.04 rabbitvcs only works for a while after a reboot.

Killing nautilus with `nautilus -q` and starting it again with `nautilus &` shows an repeating endless spam of:

```
ERROR   rabbitvcs.services.checkerservice   org.freedesktop.DBus.Python.ImportError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/services/checkerservice.py", line 185, in GenerateMenuConditions
    path_dict = self.status_checker.generate_menu_conditions(upaths)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/services/statuschecker.py", line 53, in generate_menu_conditions
    from rabbitvcs.util.contextmenu import MainContextMenuConditions
ImportError: No module named contextmenu
None

```

**Comment by syntaxerror** [comment]
I use RabittVCS quite much, haven't noticed any big difference on 16.04 vs 14.04 - it's the same instability on both it seems. :)

**Comment by adamplumb** [comment]
Based on that error I would guess that something is wrong with your install.  Try deleting your /usr/lib/python2.7/dist-packages/rabbitvcs folder and re-installing.  Or uninstalling any package you have and re-installing from our current master branch which should be improved.
