### ISSUE TITLE
Does not work correctly with non-english characters

### ISSUE THREAD

**Issue by valentas-kurauskas** [rabbitvcs/rabbitvcs#164]
RabbitVCS plugin for nautilus shows the green checkpoint icon for untracked files that contain a non-english character (for example, Lithuanian "ž"), while it should display a blue question mark for such files.

**Comment by monnerat** [comment]
There is currently an experimental branch named `encoding` in the github repo. It is supposed fixing most encoding-related problems (though filenames with invalid characters in subversion repos are not yet handled). Can you check it out and reinstall everything from there to see if your problems disappear?
Once you'll have installed this version, you must restart the service checker (menu --> RabbitVCS Git --> Settings --> Status Checker --> Restart Checker).

Thanks in advance for feedback.

**Comment by monnerat** [comment]
It should be fixed now in the master branch. If the problem persists, please reopen this issue. Thanks.
