### ISSUE TITLE
Not working with Fedora 24

### ISSUE THREAD

**Issue by dmradcliff** [rabbitvcs/rabbitvcs#165]
I am using Fedora 24 and rabbitvcs is only partially working in Nautilus.  I can commit, checkout, add, and see what has changed by the icons.  I can't update (there is no option for this), the repo browser window doesn't open, the settings window doesn't open, the diff window doesn't open and probably some more I didn't list.  This used to work in Fedora 23.

**Comment by Deevad** [comment]
Same situation on Fedora 25. Both for Nautilus and Nemo. Very untested package.

**Comment by arjones85** [comment]
Still broken. Trying to do a diff does nothing but show "loading".

Disappointed. Why is this even still in the repo?

**Comment by adamplumb** [comment]
The next release should be improved for modern systems.  I'm working on getting as many bugs ironed out as possible.
