### ISSUE TITLE
Accidental removal of files (svn)

### ISSUE THREAD

**Issue by krzysztof-kostalkowicz** [rabbitvcs/rabbitvcs#166]
What I did:
1. Right click on a directory -> Rabbit -> Repository browser
2. Changed revision, right click on a file -> Export
3. Set destination to ~, OK

Rabbit started removing all files from ~, fortunately stopped with a popup at .gnupg (no permission).

Having already lost half of my files, I repeated the same steps again, just to make sure it's Rabbit's fault. Yep. This tool is dangerous!

RabbitVCS 0.16.0
Subversion - 1.8.13.
Ubuntu 15.10

**Comment by adamplumb** [comment]
Sorry about that, should be fixed.
