### ISSUE TITLE
g-file-error-quart

### ISSUE THREAD

**Issue by ericpar** [rabbitvcs/rabbitvcs#169]
Hello,

I'm running Linux Mint 18. The suggested method of installation for Ubuntu did not work on my system so I decided to install from the sources.
I cloned the repo locally on the target computer.
I followed the instructions and installed the dependencies.
I followed the instructions in `rabbitvcs/clients/nemo/README`. (what is the `python/python-extensions` folder referring to ?)

I get the following error :

```
$ sudo nemo -q

(nemo:9632): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
sys:1: PyGIWarning: Nemo was imported without specifying a version first. Use gi.require_version('Nemo', '3.0') before import to ensure that the right version gets loaded.
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/RabbitVCS.py", line 186, in __init__
    pixbuf = GdkPixbuf.Pixbuf.new_from_file(icon_path)
GLib.Error: g-file-error-quark: Failed to open file '/usr/share/icons/hicolor/scalable/actions/rabbitvcs-settings.svg': No such file or directory (4)
Initializing folder-color-switcher extension...

```

What am I missing ?

**Comment by adamplumb** [comment]
It looks like the icons have not been installed.  Did you run `python setup.py install` on the parent folder?  That should set up your icons.

You could also set them up locally by copying the scalable folder to your ~/.local/share/icons folder.

**Comment by monnerat** [comment]
Stalled issue: closing.
