### ISSUE TITLE
can not install by python setup.py install or python3 setup.py install

### ISSUE THREAD

**Issue by lishoujun** [rabbitvcs/rabbitvcs#170]
root@qdfae:/home/lishoujun/git/rabbitvcs#  python setup.py install
running install
running build
running build_py
copying rabbitvcs/buildinfo.py -> build/lib.linux-x86_64-2.7/rabbitvcs
running install_lib
copying build/lib.linux-x86_64-2.7/rabbitvcs/buildinfo.py -> /usr/local/lib/python2.7/dist-packages/rabbitvcs
byte-compiling /usr/local/lib/python2.7/dist-packages/rabbitvcs/buildinfo.py to buildinfo.pyc
running install_data
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/rabbitvcs-0.16.0.egg-info
Writing /usr/local/lib/python2.7/dist-packages/rabbitvcs-0.16.0.egg-info
Running gtk-update-icon-cache-3.0
Traceback (most recent call last):
  File "setup.py", line 167, in <module>
    stdout=subprocess.PIPE
  File "/usr/lib/python2.7/subprocess.py", line 711, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
root@qdfae:/home/lishoujun/git/rabbitvcs#  python3 setup.py install
python3     python3.5   python3.5m  python3m  
root@qdfae:/home/lishoujun/git/rabbitvcs#  python3 setup.py install
  File "setup.py", line 163
    print "Running gtk-update-icon-cache-3.0"
                                            ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by lishoujun** [comment]
![selection_010](https://cloud.githubusercontent.com/assets/8399413/19296981/112ff77c-9073-11e6-9d9b-62501dd73be8.png)

**Comment by genpfault** [comment]
Changing

     subprocess.Popen(
        ["gtk-update-icon-cache-3.0", icon_theme_directory], 
         stdout=subprocess.PIPE
     ).communicate()[0]

to

    subprocess.Popen(
        ["gtk-update-icon-cache", os.path.join( PREFIX, icon_theme_directory )], 
        stdout=subprocess.PIPE
    ).communicate()[0]

in `setup.py` seems to let it finish on my Debian Testing system.  I know approximately zero Python so there's probably a more correct way to do it.

The `gtk-update-icon-cache-3.0` executable didn't exist on my system and `icon_theme_directory` was just `share/icons/hicolor`, missing the `/usr` prefix.

**Comment by adamplumb** [comment]
Fix in master

**Comment by lishoujun** [comment]
ok, I will try
