### ISSUE TITLE
Checkbox "show unversioned files" gets reversed meaning

### ISSUE THREAD

**Issue by AndersBillLinden** [rabbitvcs/rabbitvcs#177]
When I commit, the checkbox "show unversioned files" is initially checked, but only versioned files are shown. When checked, the unversioned files will show up.

**Comment by kwill** [comment]
Duplicate of issue https://github.com/rabbitvcs/rabbitvcs/issues/19. This is fixed in master but needs testing, acceptance and release: see merge https://github.com/rabbitvcs/rabbitvcs/pull/71

**Comment by AndersBillLinden** [comment]
Closing because of duplicate, sorry.
