### ISSUE TITLE
Documentation: which other part is RabbitVCS distributed in?

### ISSUE THREAD

**Issue by AndersBillLinden** [rabbitvcs/rabbitvcs#178]
From README.md

> RabbitVCS is now distributed in two parts. The first part is the python module that is not connected to any file manager or text editor. This is what is now known as "rabbitvcs". The second part is the series of front-ends or clients that we distribute. These consist of a Nautilus extension, a Thunar extension, a Gedit plugin, and a command line utility. All of these clients use the same python module as a back-end.

Questions that could be answered in the readme:
* Are the extensions on github as well?
* Is there a way to debug RabbitVCS? Can nautilus be run with some command line switches to include it (excluding other extensions), running it from my git clone directory?

**Comment by kwill** [comment]
You can see the extensions (called "clients") at https://github.com/rabbitvcs/rabbitvcs/tree/master/clients

I'm afraid I don't know about the debug options.

**Comment by adamplumb** [comment]
If you go to the Settings dialog there is a Logging tab and you can configure logging there.  If you set it to log to a file, it will log to ~/.config/rabbitvcs/RabbitVCS.log and you can see errors there.  If you set it to log to console, you can run Nautilus from the command line and it will show you any errors or print statements there.

**Comment by AndersBillLinden** [comment]
"Questions that could be answered in the readme" meant that I wanted the readme to cover those questions. I do not post issues on github to seek advice. :)

**Comment by adamplumb** [comment]
I'd be happy to accept a PR or patch to improve the README.  I'm going to be reworking it a bit before the next release though.
