### ISSUE TITLE
Disable rabbitVCS for git and keep SVN

### ISSUE THREAD

**Issue by biboc** [rabbitvcs/rabbitvcs#180]
Is it possible to disable rabbitVCS for git and keep SVN only?

Cheers,

**Comment by aric1987** [comment]
http://askubuntu.com/questions/484887/show-only-svn-in-rabbitvcs-context-menu

**Comment by biboc** [comment]
It's not what I meant.I want to enable rabbitVCS only on folders I want not on all nautilus.
Your answer is for disabling context-menu

**Comment by adamplumb** [comment]
There's no way to enable RabbitVCS only for specific folders.  However, I did recently add a mechanism to disable svn or git globally from the settings dialog.  You're welcome to provide a PR with this but it's not really a priority for me.
