### ISSUE TITLE
GIT marked for every folder in my computer

### ISSUE THREAD

**Issue by FireRat-137** [rabbitvcs/rabbitvcs#181]
I can not clone any other repositories of any kind, just because Git believes every file from my computer is part from some repository (nautilus 3.10.1). Every folder has a Push command.

Do note I'm just a newcomer to Linux, though reinstalling doesn't fix the issue. What can I do?

**Comment by adamplumb** [comment]
Check if you have a hidden .git folder in your $HOME folder or somewhere in a top-level.  If you keep going up directories until you're at / do you still get icons?  If you find a stray .git folder somewhere, delete it.

**Comment by monnerat** [comment]
Issue stalled: closing.
