### ISSUE TITLE
[query] How do I test a branch of RabbitVCS?

### ISSUE THREAD

**Issue by kwill** [rabbitvcs/rabbitvcs#188]
I am a software tester. I want to run a branch of RabbitVCS that is not yet packaged (or merged into `master`) so that I can provide feedback and/or confirm that it works. I want to easily revert to the stable package so that I can continue my day-to-day work when required.

Are there step-by-step instructions for:

* disabling the installed stable package
* enabling a specific branch (with Nautilus integration)
* disabling the branch
* re-enabling the stable package

*I plan to investigate the answer to this query myself, but if anyone gets there first, feel free to comment.*

**Comment by adamplumb** [comment]
I believe all you need to do is set the PYTHONPATH environment variable.  Something like in your ~/.bash_profile or ~/.bashrc:
```
export PYTHONPATH="/path/to/rabbitvcs/workingcopy:$PYTHONPATH"
```
That way it'll load from your working copy first before loading from python.

As for the nautilus integration, take a look [here](https://github.com/rabbitvcs/rabbitvcs/tree/master/clients/nautilus-3.0) at the README and that should give you some info on how to set it up.

**Comment by adamplumb** [comment]
If that satisfies your question, feel free to close this out.

**Comment by kwill** [comment]
I'm keen to try this out, even more so with the recent updates, but haven't had a chance. I'll close it as answered though. Thanks!
