### ISSUE TITLE
Git warning: empty strings as pathspecs will be made invalid in upcoming releases

### ISSUE THREAD

**Issue by kwill** [rabbitvcs/rabbitvcs#192]
Ubuntu: 17.04
RabbitVCS: 0.16-1.1
Git: 2.11.0

**Steps to reproduce:**

* Right-click on Git-managed folder
* Select "RabbitVCS Git" > "Revert"
* Select file(s) to revert
* Click "OK"

**What should happen:**

* Selected folder contents are reverted

**What happens instead:**

* Git warning appears in RabbitVCS output window: "empty strings as pathspecs will be made invalid in upcoming releases. please use . instead if you meant to match all paths"
* Selected folder contents are reverted (correct)

Presumably this will stop working completely when a future version of Git is released.

**Comment by adamplumb** [comment]
When you click the Revert menu item, it should pop up a little dialog that lets you revert specific files.  Is that not what you get? I set up git v2.13 from their repo and I can't seem to reproduce this issue.

If you can, open up the file at rabbitvcs/vcs/git/gittyup/__init__.py and in the checkout method add **print(" ".join(cmd))** underneath the cmd line.  Then post the results here when you can reproduce the issue.  Thanks.

**Comment by kwill** [comment]
I do get a Revert dialog. Updated steps to reproduce for accuracy.

My attempt to reproduce failed, so I will close this for now, assuming it was actually a repo problem, not a Rabbit problem. If it recurs I'll try the debug stops as outlined. Thanks!
