### ISSUE TITLE
RabbitVcs on Fedora 25 killed by SIGABRT, looks like on gtk

### ISSUE THREAD

**Issue by abregar** [rabbitvcs/rabbitvcs#193]
Hi,
I am trying to setup RabbitVcs on Fedora 25 (both variants - official packages and latest master checkout). Tried caja, thunar, nemo, nautilus and they all crash similar with:
```
[xcb] Unknown request in queue while dequeuing    
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called   
[xcb] Aborting, sorry about that.   
python: xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.   
```
There is a coredump created:
```
Jun 20 10:57:49 host audit[17214]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=18 pid=17214 comm="python" exe="/usr/bin/python2.7" sig=6 res=1
Jun 20 10:57:49 host abrt-hook-ccpp[17221]: Process 17214 (python2.7) of user 1000 killed by SIGABRT - dumping core
```
With attached back-trace and cmdline in file core_meta.zip.
[cmdline.txt](https://github.com/rabbitvcs/rabbitvcs/files/1088328/cmdline.txt)
[core_backtrace.txt](https://github.com/rabbitvcs/rabbitvcs/files/1088329/core_backtrace.txt)

I would appreciate some hint where to look to pinpoint potential problem.
Thanks in advance

**Comment by adamplumb** [comment]
I've never seen this error but it seems to be related to something called [xcb](https://xcb.freedesktop.org/XcbPythonBinding/).  Are you doing anything with xcb that you know about?  I'm not really familiar with it to be honest so any research you can do would be good.

**Comment by adamplumb** [comment]
Can you install the cli client and try to run some commands?  I would like to see if this happens even outside any file manager extensions.

**Comment by abregar** [comment]
Thank you for taking a look into this. Tried cli, some commands (eq. diff) are opening ui fine, while for eq. log crashes the same way as above. Frogot to attach dmesg line yesterday:
```bash
[Wed Jun 21 09:46:35 2017] python[21277]: segfault at 84 ip 00007f788ad2e736 sp 00007ffda4c3dba0 error 4 in libgdk-x11-2.0.so.0.2400.31[7f788acba000+bc000]
```

**Comment by adamplumb** [comment]
This is some kind of threading issue with the UI that must affect the log dialog.  I do get crashes on my install every now and then but I've had a hard time figuring them out, they seem pretty random for me.  I'll keep a look out though and try to look into it the next time it happens.  Also, feel free to look into it yourself if you like.  Sorry I couldn't be more helpful.

**Comment by abregar** [comment]
Quick/brief look into pointed direction - I have modified /lib/python2.7/site-packages/rabbitvcs/util/decorators.py on
```
...
import gtk
gtk.gdk.threads_init()
...
```
Does not crash anymore.

**Comment by adamplumb** [comment]
Oh great! Good to know.
