### ISSUE TITLE
"Show unversioned files" check-box in commit dialog misbehaves

### ISSUE THREAD

**Issue by tylla** [rabbitvcs/rabbitvcs#201]
I'm using the latest version (0.16.0) on Debian Jessie and the "Show unversioned files" check-box in the Commit dialog works quite strange. I don't know how I got in this state (possibly I made something wrong) but currently what it does when the Commit dialog is opened and cancelled multiple times in a row is this:
CHECK-BOX STATE, FILES SHOWN -> ACTION TAKEN, RESULT

1. un-checked, no files
2. checked, no files
3. checked, no files -> un-checking, file appears -> checking, file disappears
4. checked, no files
5. checked, no files -> un-checking, file appears
6. un-checked, no files
7. checked, no files
8. checked, no files -> un-checking, file appears
9. un-checked, no files -> checkin, file appears
10. ...
13. un-checked, no files -> checking, file appears
14. un-checked, no files -> checking, file appears -> un-checking, file disappears
15. GOTO 2.

I would say a typo somewhere. :)
If anymore information is needed I'm happy to provide, just please indicate so.

**Comment by pczekalski** [comment]
I agree. If you leave dialog box with "Show Unversioned Files" checked (so next time you open it, it is checked by default), then on next open it behaves like it wasn't checked (no unversioned files are shown) and the logic is opposite to the expected one - unchecked shows, checked does not. I guess there is a mistake in initial dialog box processing - flag is checked on change, not on initial and its value is not checked at all.

**Comment by gary17** [comment]
FYI, as of Ubuntu 18.04 _bionic_ with RabbitVCS 0.16, the issue still has not been fixed (for over a year).

Uninstall `rabbitvcs-core` and re-install manually from the `master` GitHub repo. Make sure to install RabbitVCS Nautilus 3 extension as well, or your right-click menu is going to keep crashing.

**Comment by gary17** [comment]
FYI, as of Ubuntu 18.04 _bionic_ with RabbitVCS 0.16, the issue still has not been fixed (for over a year).

Uninstalling Ubuntu `rabbitvcs-core` 0.16 and re-installing 0.17 manually from the `master` GitHub repo fixes the "Show unversioned files" problem, but causes the Nautilus 3 right-click menu extension to behave erratically.

**Comment by gary17** [comment]
FYI, as of Ubuntu 18.04 bionic with RabbitVCS 0.16, the issue still has not been fixed (for over a year).

Uninstalling Ubuntu `rabbitvcs-core` 0.16 and re-installing 0.17 manually from the `master` GitHub repo fixes the "Show unversioned files" problem, but causes the Nautilus 3 right-click menu extension to sometimes behave erratically.

What works is to manually patch Ubuntu `rabbitvcs-core` 0.16 with [this patch](https://github.com/rabbitvcs/rabbitvcs/pull/71/files).

**Comment by monnerat** [comment]
Fixed in master by commit https://github.com/rabbitvcs/rabbitvcs/commit/c4ac1ce80bd0ab0bf6adabbcc21d63165879b76f.
Closing.
