### ISSUE TITLE
Sort in Repository Browser is incorrect

### ISSUE THREAD

**Issue by tylla** [rabbitvcs/rabbitvcs#202]
The Repository Browser file list is sorted case sensitively while all my other Nautilus windows are sorted according to my locale case insensitively.

I would say the file list is using the LOCALE or LC_COLLATE set to C instead of using the settings from the environment.

I'm using RabbitVCS 0.16.0 on Debian Jessie, my LOCALE is set to a mix of en_US.utf8 and hu_HU.utf8 which - as I know, and Nautilus agrees - are both case insensitive.

Please indicate if I can provide any other information.

**Comment by monnerat** [comment]
Should be fixed by commit 832b1e8. If the problem persists, please reopen this issue. Thanks.
