### ISSUE TITLE
nautilus extension not working on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by philipraets** [rabbitvcs/rabbitvcs#204]
Hi,

I've tried to install the latest version (0.17) on openSUSE Tumbleweed, but the nautilus extension doesn't work. In the console I get the following error:

```
Aug 18 10:25:52 HOSTNAME org.gnome.Nautilus[3665]: Traceback (most recent call last):
Aug 18 10:25:52 HOSTNAME org.gnome.Nautilus[3665]:   File "/usr/share/nautilus-python/extensions/RabbitVCS.py", line 460, in get_background_items_full
Aug 18 10:25:52 HOSTNAME org.gnome.Nautilus[3665]:     path = rabbitvcs.util.helper.unquote_url(self.get_local_path(item.get_uri()))
Aug 18 10:25:52 HOSTNAME org.gnome.Nautilus[3665]:   File "/usr/lib/python2.7/site-packages/rabbitvcs/util/helper.py", line 845, in unquote_url
Aug 18 10:25:52 HOSTNAME org.gnome.Nautilus[3665]:     path_unquoted = urllib.unquote(path).decode('utf-8')
Aug 18 10:25:52 HOSTNAME org.gnome.Nautilus[3665]: NameError: global name 'urllib' is not defined
```

This is with Python 2.7.13
To install I did "python setup.py install" as su and then copied the extension to "/usr/lib64/nautilus-python/extensions"

If I install version 0.16 from OBS, then it's working.

Anything I can try to get this working?

Thanks

**Comment by adamplumb** [comment]
You should install the v0.17.1 tag which fixes that issue.  I should have
made an announcement about it but I forgot.

**Comment by philipraets** [comment]
Thanks,

now it works :-)

And thanks for all the work in this project.
