### ISSUE TITLE
Support for GitHub and BitBucket

### ISSUE THREAD

**Issue by KevinCee915** [rabbitvcs/rabbitvcs#206]
Hiya! I was wondering if the latest version of RabbitVCS supports accessing and working with GitHub and/or BitBucket repos?

**Comment by adamplumb** [comment]
It will work with any type of got repository. Is there anything in
particular you're trying to do that you're having trouble doing with
rabbitvcs?

**Comment by KevinCee915** [comment]
I was trying to look for any docs on how to configure a bitbucket or GitHub repo on your site but couldn't find any.

**Comment by adamplumb** [comment]
All you need to do is enter the GitHub repo url into the clone dialog. Or
for adding a GitHub or bitbucket remote, there is a Remotes dialog that
will let you do that

**Comment by KevinCee915** [comment]
Wonderful, thx!
