### ISSUE TITLE
Include the menu items in the "crumble/path bar" too

### ISSUE THREAD

**Issue by tylla** [rabbitvcs/rabbitvcs#220]
Nautilus lists the current path in a click-able "Crumbles" control at the top of the window. (what is the proper name of it???)
One can right click on these buttons as well to make some useful things.
It would be really cool if the usual VCS controls would appear in this context-menu as well. This would be handy especially in the cases when there is a big directory that you want to Update/Commit and where you can't find an empty space between the file list to right click. There you could simply right click on the actual folder name in the crumbles bar and perform the action as usual without the need to go one level up, perform the action and finally descend again into the named folder.

**Comment by adamplumb** [comment]
This is a nice idea! Unfortunately it is something that would need to be done inside Nautilus itself.  They would need to update their extension framework to request custom menu items from extensions.  If you want to pursue this, my recommendation would be to contact Nautilus on their mailing list and see what kind of response you get.

**Comment by adamplumb** [comment]
If they do end up implementing it, I'd be happy to update RabbitVCS.
