### ISSUE TITLE
WARNING: All files and folders DELETED on Export!

### ISSUE THREAD

**Issue by dmanolov** [rabbitvcs/rabbitvcs#222]
I have found a HUGE and DANGEROUS bug in RabbitVCS: it deletes ALL FILES and FOLDERS from folder, selected for export and gives NO warning before that. How it happens:

I wanted to export previous version of a file to check something. In export dialog for export destination  I selected the root folder of a drive, that has many files and folders in it. I assumed, that it will pull the requested exported revision of the file and will create one new file in that folder. And when I clicked OK, it deleted ALL SUBFOLDERS and files in that folder and gave me NO warning before that! Please fix this so no one have troubles like me! It has deleted more than 50 GB of data without even one warning! I have checked the export dialog later - there is no checkbox "Delete all", "Purge", "Clear" etc. to give me at least some idea what will happen.

I'm new to RabbitVCS, but I have used other VCS systems before. I use version 0.16-1 with SVN on Ubuntu 16.04.

**Comment by adamplumb** [comment]
Hey I'm sorry this happened to you.  Unfortunately this is a bug in the export function of v0.16.  I would recommend you upgrade to the latest v0.17.1 release, which fixes this bug as well as a bunch of others.
