### ISSUE TITLE
ModuleNotFoundError: No module named 'rabbitvcs'

### ISSUE THREAD

**Issue by philipraets** [rabbitvcs/rabbitvcs#229]
Since this week on my openSUSE Tumbleweed machine (updated to latest snapshot, 64bit) I have the following error when starting nautilus:

```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/RabbitVCS.py", line 70, in <module>
    from rabbitvcs.vcs import VCS
ModuleNotFoundError: No module named 'rabbitvcs'
```

I've uninstalled and installed it again, but the error remains, version 0.17.1 and from master.
I have noticed that I had some updates to python

How can I debug this so I know what went wrong?

Thanks,

Philip

**Comment by adamplumb** [comment]
The error is telling me that it can't find the rabbitvcs module.  There is a module search path which is usually in a place like `/usr/lib64/python3.6/site-packages/` or maybe `/usr/lib/...`.  See if you can find where the rabbitvcs module got installed to and why it's not in the python search path.

You should be able to run the python command shell and type:
```
from rabbitvcs.vcs import VCS
```

**Comment by philipraets** [comment]
When I use the python command shell, I don't get errors, it can find the module rabbitvcs (which is in /usr/lib/python2.7/site-packages/rabbitvcs):

```
praets@PRAETS:~> nautilus
Initializing nautilus-image-converter extension
Initializing nautilus-dropbox 2015.10.28
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/RabbitVCS.py", line 70, in <module>
    from rabbitvcs.vcs import VCS
ModuleNotFoundError: No module named 'rabbitvcs'
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/RabbitVCS.py", line 70, in <module>
    from rabbitvcs.vcs import VCS
ModuleNotFoundError: No module named 'rabbitvcs'
praets@PRAETS:~> python
Python 2.7.14 (default, Oct 12 2017, 15:50:02) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rabbitvcs
>>> import inspect
>>> inspect.getfile(rabbitvcs)
'/usr/lib/python2.7/site-packages/rabbitvcs/__init__.pyc'
>>> 
```

**Comment by philipraets** [comment]
When I tried installing with `python3 setup.py install` I get the following error:

```
praets@PRAETS:~/Downloads/rabbitvcs-0.17 (2).1> nautilus
Initializing nautilus-image-converter extension
Initializing nautilus-dropbox 2015.10.28
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/RabbitVCS.py", line 71, in <module>
    import rabbitvcs.vcs.status
  File "/usr/lib/python3.6/site-packages/rabbitvcs/vcs/status.py", line 403, in <module>
    class TestStatusObjects(unittest.TestCase):
  File "/usr/lib/python3.6/site-packages/rabbitvcs/vcs/status.py", line 408, in TestStatusObjects
    os.path.join(base, chr(x)) for x in range(97,123) 
  File "/usr/lib/python3.6/site-packages/rabbitvcs/vcs/status.py", line 408, in <listcomp>
    os.path.join(base, chr(x)) for x in range(97,123) 
NameError: name 'base' is not defined
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/RabbitVCS.py", line 71, in <module>
    import rabbitvcs.vcs.status
  File "/usr/lib/python3.6/site-packages/rabbitvcs/vcs/status.py", line 403, in <module>
    class TestStatusObjects(unittest.TestCase):
  File "/usr/lib/python3.6/site-packages/rabbitvcs/vcs/status.py", line 408, in TestStatusObjects
    os.path.join(base, chr(x)) for x in range(97,123) 
  File "/usr/lib/python3.6/site-packages/rabbitvcs/vcs/status.py", line 408, in <listcomp>
    os.path.join(base, chr(x)) for x in range(97,123) 
NameError: name 'base' is not defined
```

**Comment by philipraets** [comment]
I have it somewhat working now (the basics: update, commit, get lock, release lock, add, show_log, ...) by switching to the gtk3 brand and do some minor modifications:

in rabbitvcs/vcs/status.py at line 405:
move base outside the class so it's defined

in rabbitvcs/util/helper.py at line 848:
remove .decode('utf-8') from path_unquoted = unquote(path).decode('utf-8')

and then the modifications in the ui files (basically refactor the imports and a few minor fixes in the xml like orientation)

not everything works, but my knowledge of python and gtk is very limited

Anyway, thanks for this nice program

**Comment by adamplumb** [comment]
Hi Phillip I'm glad you were able to get it working. If you made some fixes
to the gtk3 branch would you mind opening up a pull request with your fixes?

**Comment by philipraets** [comment]
I've created a pull request #232 with the fixes I've made to get basic functionality for SVN working (update, commit, add, lock and unlock, rename, ...). I haven't tested git, because we mainly use SVN here at work.

**Comment by philipraets** [comment]
I switched to the latest version, and don't have any problems so far. Thank you
