### ISSUE TITLE
Unable to diff XLS files i.e. of binary format

### ISSUE THREAD

**Issue by bbhanus** [rabbitvcs/rabbitvcs#233]
Can help us in getting the difference b/w the file stored in SVN and local file of format xls i.e. basically excel sheets.

**Comment by kwill** [comment]
Unfortunately diffing binary files isn't a feature of RabbitVCS or SVN. You could try:

* converting the files to CSV format and comparing those with a regular plaintext diffing tool
* doing a search for "xls diff" and/or asking on https://superuser.com

**Comment by monnerat** [comment]
RabbitVCS diff and compare features only deal with text files.
You have to get both versions of your .xls files on your local storage and use some external diff program able to handle .xls format.
Closing.
