### ISSUE TITLE
Support git commit --signoff

### ISSUE THREAD

**Issue by david-libremone** [rabbitvcs/rabbitvcs#237]
**User story:** I am a developer committing contributions to a project. I want to sign-off my commits, so that I can meet the contribution requirements of the project.

**Background:** Some projects require contributors to "sign off" their commits for licensing purposes. The `git commit --signoff` command was created specifically for this purpose. From the [git documentation](https://git-scm.com/docs/git-commit#git-commit---signoff):

> --signoff
> Add Signed-off-by line by the committer at the end of the commit log message. The meaning of a signoff depends on the project, but it typically certifies that committer has the rights to submit this work under the same license and agrees to a Developer Certificate of Origin (see http://developercertificate.org/ for more information).

**Suggested solution:** Add a "[ ] Sign off" tickbox to the RabbitVCS commit window.

**Notes:** This is not the same as supporting the `git commit --gpgsign` command, which would require a separate tickbox/field.

**Comment by monnerat** [comment]
Since it can be easily added manually or cut-paste to the commit message, RabbitVCS won't support this option.
Thanks for the suggestion.

**Comment by david-libremone** [comment]
@monnerat I agree that achieves the result, but it would be quite a workaround for someone who does it regularly, or doesn't want to make a mistake.

Another option that occurs to me is a global setting that prepopulates the commit message with the "signed-off-by" value. This would require no UI changes.

Would you accept a patch that implemented this?

**Comment by adamplumb** [comment]
That seems like a reasonable request, as long as you can submit a patch.
It would probably make sense to include a change to the git settings dialog
page and maybe one in the commit screen to override it. But if you want to
just start with the settings dialog that would work.

**Comment by monnerat** [comment]
Agreed with Adam: having a commit message pattern in the settings allows presetting it with every text a commiter may need and is far less specific than a signoff option.

**Comment by monnerat** [comment]
Commit https://github.com/rabbitvcs/rabbitvcs/commit/52075100a39e4c5835c6e9fc9d065fe3b2dc7391 implements what has been discussed here. It is also applied to the subversion commit dialog.
