### ISSUE TITLE
wiki.rabbitvcs.org uses reCAPTCHA v1, which has shut down

### ISSUE THREAD

**Issue by pklapperich** [rabbitvcs/rabbitvcs#238]
I tried to make an account for wiki.rabbitvcs.org and was presented with this:

![image](https://user-images.githubusercontent.com/12666157/44106328-f8f47afe-9fb9-11e8-9a8b-b8935263ab42.png)

Recaptcha shut down a while ago, last summer I think. The page should be updated to use reCAPTCHA v2 (the one that shows pictures of stop signs).

**Comment by adamplumb** [comment]
Hi, I've updated registration page to use a working pre-registration system.  Thanks for the bug report!
