### ISSUE TITLE
Error during install on debian

### ISSUE THREAD

**Issue by tylla** [rabbitvcs/rabbitvcs#241]
While trying the recommended install method for the latest version (0.17) I was stopped with an error:
```
    running install
    running build
    running install_data
    error: can't copy 'rabbitvcs/util/configspec/configspec.ini': doesn't exist or not a regular file
```

I suspect that `setup.py` should contain the real path of the `configspec.ini` so by correcting line 103:
    ["rabbitvcs/util/configspec/configspec.ini"]
into
    ["util/configspec/configspec.ini"]
the install completed successfully.

Is this valid, or there was some other error I missed and the install completed only by chance? :)
I am creating a PR in case my solution is really THE solution.

**Comment by freddii** [comment]
the fix broke it for me:
copying MAINTAINERS -> /usr/share/doc/rabbitvcs
error: can't copy 'util/configspec/configspec.ini': doesn't exist or not a regular file

changing it back to rabbitvcs/util/configspec/configspec.ini solved it for me.

**Comment by karate** [comment]
Also broken on Fedora 28.

I think this should be reverted.

**Comment by karate** [comment]
@adamplumb should we close this issue?

**Comment by adamplumb** [comment]
Sorry about this guys, I didn't actually test the PR before merging it in.  I think we should close this.

**Comment by tylla** [comment]
Sorry from me as well.
Now if only I could find out why this worked on my system.
