### ISSUE TITLE
Any chance to update version for CentOS7

### ISSUE THREAD

**Issue by mmarquezvacas** [rabbitvcs/rabbitvcs#243]
Hi. I was wondering if there could be a release for Centos 7 (RHEL 7).

**Comment by armando-basile** [comment]
+1

**Comment by adamplumb** [comment]
I'm not making releases for specific distributions anymore, so my advice would be to download the latest release directly from github and install it manually using the python setup process, and then installing the extension you want.  It's pretty straightfoward to do actually.
