### ISSUE TITLE
"Show changes against previous revision" is not working

### ISSUE THREAD

**Issue by karate** [rabbitvcs/rabbitvcs#244]
In the Log window, if I select a revision and right-click on a file, the "Show changes against previous revision" option doesn't do anything.

In systemd I see the following error:

```
Traceback (most recent call last):
  File "/home/dt/.local/lib/python2.7/site-packages/rabbitvcs/ui/log.py", line 1537, in show_changes_previous_revision
    "%s@%s" % (url, rev_last),
NameError: global name 'rev_last' is not defined
```

**Comment by adamplumb** [comment]
Thanks for this.  I've applied your fix and a few others I made myself to fix some issues i noticed.
