### ISSUE TITLE
Commit dialog "Found X item(s)" misleading

### ISSUE THREAD

**Issue by tylla** [rabbitvcs/rabbitvcs#248]
Currently the commit dialog says on the bottom left, near the Refresh button: "Found X item(s)"
But this is a bit misleading as - by default - it does not account for possible unversioned files, so one can go ahead without noticing that s/he is missing a few files from the commit. Or the "Show unversioned files" check-box must be kept checked.
As a solution I would suggest a small change in behaviour.
The text should be changed to something along the line: "Found X change(s) and Y unversioned file(s)".
This should get displayed invariably of the Show unversioned check-box.
As I deducted the information must be ready at hand as there is no delay in changing the displayed number when changing the check-box, so this must be a really simple change. I couldn't find the code fragment in question so that I could make a PR, but if someone can point me to the right direction I could take a chance fixing it myself.
BTW: if it matters, I'm using the Nautilus client with RabbitVCS 0.17.0

**Comment by adamplumb** [comment]
The code for that is here: https://github.com/rabbitvcs/rabbitvcs/blob/master/rabbitvcs/ui/commit.py#L249.

Feel free to try this out and see how it fits in the dialog.  Unfortunately this label change will break the translated versions of this label.
