### ISSUE TITLE
Won't build on RHEL5.10

### ISSUE THREAD

**Issue by kmasaryk** [rabbitvcs/rabbitvcs#25]
I've tried following the old instructions at http://wiki.rabbitvcs.org/wiki/install/rhelcentos5 but it appears that the current master branch of rabbit won't build. I see the following syntax errors which I'm guessing may be caused by the version of python available for RHEL5:

---

[root@foo rabbitvcs-master]# python setup.py install
running install
running build
running build_py
copying rabbitvcs/buildinfo.py -> build/lib/rabbitvcs
running install_lib
copying build/lib/rabbitvcs/buildinfo.py -> /usr/lib/python2.4/site-packages/rabbitvcs
byte-compiling /usr/lib/python2.4/site-packages/rabbitvcs/ui/action.py to action.pyc
  File "/usr/lib/python2.4/site-packages/rabbitvcs/ui/action.py", line 640
    finally:
          ^
SyntaxError: invalid syntax
byte-compiling /usr/lib/python2.4/site-packages/rabbitvcs/ui/diff.py to diff.pyc
  File "/usr/lib/python2.4/site-packages/rabbitvcs/ui/diff.py", line 241
    finally:
          ^
SyntaxError: invalid syntax
byte-compiling /usr/lib/python2.4/site-packages/rabbitvcs/buildinfo.py to buildinfo.pyc
byte-compiling /usr/lib/python2.4/site-packages/rabbitvcs/vcs/svn/**init**.py to **init**.pyc
  File "/usr/lib/python2.4/site-packages/rabbitvcs/vcs/svn/**init**.py", line 258
    depth = pysvn.depth.infinity if recurse else pysvn.depth.empty
                                  ^
SyntaxError: invalid syntax
running install_data
Running gtk-update-icon-cache
No theme index file in 'share/icons/hicolor'.
If you really want to create an icon cache here, use --ignore-theme-index.

[root@foo rabbitvcs-master]# lsb_release -a
LSB Version:    :core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 5.10 (Tikanga)
Release:    5.10
Codename:   Tikanga

[root@foo rabbitvcs-master]# python -V
## Python 2.4.3

Any suggestions on how to get a modern version of rabbit to work on RHEL5? I tried downloading and building python 2.7 from source and installing in /usr/local/bin but then I get errors from building rabbit or one of the other dependencies about not finding the python 2.7 devel libs.

Are the RHEL/CentOS 5 instructions just totally outdated or am I missing something? Not sure what else to try at this point.

**Comment by adamplumb** [comment]
Obviously this is quite late and I can't imagine you're still running CentOS 5.x (I'd hope not), but I fixed these minor errors.
