### ISSUE TITLE
error: can't copy 'util/configspec/configspec.ini': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by Jenfong** [rabbitvcs/rabbitvcs#250]
copying data/icons/hicolor/16x16/actions/rabbitvcs-push.png -> /usr/local/share/icons/hicolor/16x16/actions
creating /usr/local/share/doc/rabbitvcs
copying AUTHORS -> /usr/local/share/doc/rabbitvcs
copying MAINTAINERS -> /usr/local/share/doc/rabbitvcs
creating /usr/local/share/rabbitvcs
error: can't copy 'util/configspec/configspec.ini': doesn't exist or not a regular file

-----setup.py------
# Config parsing specification
config_spec = [(
    "share/rabbitvcs",
    ["util/configspec/configspec.ini"]
)]

**Comment by adamplumb** [comment]
Can you try changing this line to
```
    ["rabbitvcs/util/configspec/configspec.ini"]
```

**Comment by monnerat** [comment]
Master specifies it as `["rabbitvcs/util/configspec/configspec.ini"]` since https://github.com/rabbitvcs/rabbitvcs/commit/5e5c012b0e04e20ef22598b6546780a273d8f0e4 and it works.
Closing.
