### ISSUE TITLE
Not working on Fedora 29 on Nemo file manager

### ISSUE THREAD

**Issue by juanradiego** [rabbitvcs/rabbitvcs#252]
Launching from terminal outputs this:
```
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/RabbitVCS.py", line 71, in <module>
    import rabbitvcs.vcs.status
  File "/usr/lib/python3.7/site-packages/rabbitvcs/vcs/status.py", line 403, in <module>
    class TestStatusObjects(unittest.TestCase):
  File "/usr/lib/python3.7/site-packages/rabbitvcs/vcs/status.py", line 408, in TestStatusObjects
    os.path.join(base, chr(x)) for x in range(97,123) 
  File "/usr/lib/python3.7/site-packages/rabbitvcs/vcs/status.py", line 408, in <listcomp>
    os.path.join(base, chr(x)) for x in range(97,123) 
NameError: name 'base' is not defined
```

**Comment by X3MBoy** [comment]
I'm having the same issue

`# ealucena @ MOEALUCENA in ~ [14:51:40] 
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 29 (Twenty Nine)
Release:	29
Codename:	TwentyNine

# ealucena @ MOEALUCENA in ~ [14:51:47] 
$ uname -a
Linux MOEALUCENA 4.20.10-200.fc29.x86_64 #1 SMP Fri Feb 15 18:33:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

# ealucena @ MOEALUCENA in ~ [14:51:48] 
$ python -V
Python 2.7.15

# ealucena @ MOEALUCENA in ~ [14:51:53] 
$ python3 -V
Python 3.7.2

# ealucena @ MOEALUCENA in ~/.config/rabbitvcs [14:52:34] C:1
$ dnf info rabbitvcs-core-0.17.1-9.fc29.noarch rabbitvcs-nemo-0.17.1-9.fc29.noarch 
Installed Packages
Name         : rabbitvcs-core
Version      : 0.17.1
Release      : 9.fc29
Architecture : noarch
Size         : 1.5 M
Source       : rabbitvcs-0.17.1-9.fc29.src.rpm
Repository   : @System
From repo    : updates
Summary      : Common package of RabbitVCS
URL          : http://rabbitvcs.org
License      : GPLv2+
Description  : Contains files shared between the RabbitVCS extensions.

Name         : rabbitvcs-nemo
Version      : 0.17.1
Release      : 9.fc29
Architecture : noarch
Size         : 24 k
Source       : rabbitvcs-0.17.1-9.fc29.src.rpm
Repository   : @System
From repo    : updates
Summary      : Nemo extension for RabbitVCS
URL          : http://rabbitvcs.org
License      : GPLv2+
Description  : An extension for Nemo to allow better integration with the
             : source control system.
`

**Comment by monnerat** [comment]
This now works from a master branch snapshot. For Fedora package bugs (or request for a package update), use https://bugzilla.redhat.com/
