### ISSUE TITLE
Rename 'Merge' to 'Graft'

### ISSUE THREAD

**Issue by MasonStooksbury** [rabbitvcs/rabbitvcs#254]
With all of the botanical language used in Subversion and Git-style version control (branch, trunk, root, etc.) why do we use the word "merge" when fusing a branch to trunk/root instead of "graft"?

If it's an easy fix, it seems to me to make more sense/fun to use "graft".

**Comment by kwill** [comment]
I haven't used Subversion for a while, but in Git [merge has a specific meaning](https://git-scm.com/docs/git-merge). Anyone reading a Git tutorial wouldn't be able to find the "Merge" function if it was renamed to "Graft".

A bit more obscurely, [graft is also a Git concept](https://git-scm.com/docs/git-replace) in the "Replace" command. I think fewer users would be in a position to confuse it, but if they tried searching for "git graft" what they found would be confusing.

**Comment by MasonStooksbury** [comment]
While I agree that merge has a specific meaning, this doesn't necessarily mean that it can't be renamed. If someone had originally named it "graft" and applied the same definition, no one would have any qualms. They would just learn what it is.

In regards to your second point, I also agree. A renaming would potentially cause some issues in regards to peoples initial impression of what the command would do. But I don't think this would be any large issue that couldn't be easily overcome by a simple Google search. People have learned varying lingos for a long time and I think people are able to understand "Oh, merge means the same thing in Git that graft means in Subversion". 

Lastly, I would probably only change Subversion, since that's what I'm using, but also because it doesn't currently have any existing "graft" concepts like Git does. I agree, it would be hard to change it everywhere, but I'm currently only arguing for Subversion.

Thanks for the response!

**Comment by monnerat** [comment]
Thanks for your vocabulary thoughts. However, implementing RabbitVCS own vocabulary may lead to confusions with VCS specific ones.
Subversion and git users are accustomed to each VCS vocabulary and changing it for the sake of unification between VCSs will only puzzle them.
Thus this will not be implemented.
