### ISSUE TITLE
No emblems after new MIME type registered

### ISSUE THREAD

**Issue by vittopascu** [rabbitvcs/rabbitvcs#256]
Dear all,

I am using linux Mint 19.1 Cinnamon with nautilus, but I noticed this issue on Ubuntu Gnome 3 as well. I have RabbitVCS installed and everything works well.

However, I had to register a new MIME type by following the instructions:
https://developer.gnome.org/integration-guide/stable/mime.html.en

The mime type is now successfully registered but RabbitVCS won't apply emblems on files of the new type. De-registering the new mime type by deleting the corresponding .xml file and re-updating mime database makes the emblems reappear.

I also tried to change icon theme without success.

**Comment by monnerat** [comment]
I made some testing and I can reproduce. However, it seems Nautilus itself refuses to set the emblem (I don't know under which precise condition). I think nothing can be done in RabbitVCS to overcome this problem.
This does not occur with Caja that has a RabbitVCS client very similar to Nautilus one.

**Comment by vittopascu** [comment]
Hello, I actually solved the problem. Instead of manually adding the mime types I began to use this tool https://forums.linuxmint.com/download/file.php?id=49217 that a very friendly guy on the linux Mint forums packaged for all of us. When registering new mimes with that script the emblems appear regularly.

**Comment by monnerat** [comment]
> I actually solved the problem ...

Thank you for your reply. As a conclusion, we can surely assume the problem is outside RabbitVCS and this issue is resolved.
