### ISSUE TITLE
 bug update for rabbitvcs 0.17

### ISSUE THREAD

**Issue by lucasisoppo** [rabbitvcs/rabbitvcs#263]
steps:
1- I installed the dependencies as readme of git
2- Replace files in the /usr/lib/python2.7/dist-packages/rabbitvcs folder
3- I ran setup.py
4- Replace RabbitVCS.py from the /usr/share/nemo-python/extensions folder
5- I ran:
        $ nemo -q
        $ pgrep -f service.py | xargs kill
        $ nohup nemo > /dev/null &
6- Restart the system

You are not displaying more of the RabbitVcs icons in the menu, and running the nemo displays the following log:

Error: section HideItem:svn doesn't exist
Error: section HideItem:git doesn't exist
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/RabbitVCS.py", line 87, in <module>
    import rabbitvcs.ui.property_page
  File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/ui/property_page.py", line 31, in <module>
    import rabbitvcs.ui.widget
  File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/ui/widget.py", line 35, in <module>
    gi.require_version("GtkSpell", "3.0")
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSpell not available

**Comment by gabrielfin** [comment]
I'm having the same error, even though I have python-gtkspellcheck installed.

A workaround for this error is modifying `/usr/lib/python2.7/dist-packages/rabbitvcs/ui/widget.py` line 38:
```
except ImportError:
```
with:
```
except ValueError:
```
