### ISSUE TITLE
Viewing diff with Meld does not work

### ISSUE THREAD

**Issue by gabrielfin** [rabbitvcs/rabbitvcs#266]
I've just installed version 0.17 on Ubuntu MATE 18.04. When trying to view a diff, Meld doesn't open. System monitor shows the corresponding Meld process running, with status "Sleeping", but no Meld window opens. I have tried upgrading to Meld 3.20, but the problem persists. Other tools like Fldiff and Diffuse work without issue.

Where can I look for errors or log messages?

**Comment by PaulMEdwards** [comment]
You can run `nautilus` in a terminal to observe the output when you try to perform the meld diff. I did so and observed the following message when I try to :

```Usage: 
  meld                              Start with an empty window
  meld <file|folder>                Start a version control comparison
  meld <file> <file> [<file>]       Start a 2- or 3-way file comparison
  meld <folder> <folder> [<folder>] Start a 2- or 3-way folder comparison

Error: Cannot compare a mixture of files and directories```

**Comment by PaulMEdwards** [comment]
There are at least 2 work-arounds I have found:

1. Run Meld and select the "Version control view" option from the New Comparison screen, then select your project directory from the drop-down which appears, then click "Compare".
2. Right-click the project directory in Nautilus and choose the "Commit" menu item which will show a dialog of the pending changes, then double-click any item listed to open a side-by-side view in Meld.

**Comment by gabrielfin** [comment]
The problem may not have been related to RabbitVCS. For some reason, ~/.local/share/meld was owned by root. Chown'ing that folder to myself fixed the issue.
