### ISSUE TITLE
Cant install rabbit vcs in oracle linux 7

### ISSUE THREAD

**Issue by govindarajan26** [rabbitvcs/rabbitvcs#277]
Issue is with the python version. Oracle linux 7 comes with python 2.7 dy default. but we are expecting 2.6

Any help/advice is appreciated ?

-> Finished Dependency Resolution
Error: Package: rabbitvcs-core-0.14.2.1-5.el6.noarch (epel)
           Requires: python(abi) = 2.6
           Installed: python-2.7.5-86.0.1.el7.x86_64 (@ol7_latest)
               python(abi) = 2.7
               python(abi) = 2.7

Thanks
Govind.

**Comment by monnerat** [comment]
Definitively, this is a packaging problem:
Rabbitvcs 0.14 is a very old version and epel packager(s) should have produced a new rabbitvcs package when epel7 python was upgraded.

Nothing can be done upstream: you should either report the problem for the epel distribution at https://bugzilla.redhat.com/ and wait for a packager to upgrade, or install manually from git master branch.
