### ISSUE TITLE
rabitvcs don't work like tortoisegit: repository name

### ISSUE THREAD

**Issue by heavyblack1** [rabbitvcs/rabbitvcs#278]
if i want clone repo in nautilus rabitvcs
https://github.com/monarezio/kotlin-minesweeper
this create folder github.com not repo name which is kotlin-minesweeper
could you make option in settings or fix this unwanted behavior i think people prefer repo name not domain name like me is annoying to always rename to repo name
thanks

**Comment by monnerat** [comment]
This has been fixed in commit https://github.com/rabbitvcs/rabbitvcs/commit/33c295b21cb3b8c72cdf35022e7951982cd7b0dc and reinstalling from master branch should resolve your problem. If the latter persists, please reopen this issue, thanks.
