### ISSUE TITLE
Removal of python2 and pygtk2

### ISSUE THREAD

**Issue by rickysarraf** [rabbitvcs/rabbitvcs#279]
## Description
Debian is targeting the removal [python2](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939024) and [pygtk2](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885476) for the next release, **Bullseye**
RabbitVCS currently depends on these packages and thus is slated for removal from the Debian repository soon.

I believe there has been some work (unreleased?) to port RabbitVCS to py3.
Is there a release planned to switch to py3 and pygtk3 ?

**Comment by adamplumb** [comment]
Thanks for checking in! Our master branch is now free of python 2 and
pygtk2 and has fully moved on to gtk3 and gobject introspection. There
might be some old clients that still depend on gtk2 but they can be
packaged separately.

We should tag master and do a proper release. That's something I can
probably do soon.

We don't have anyone packaging new rabbitvcs releases so someone will need
to do that.

**Comment by PaulMEdwards** [comment]
Please fix this issue's title to reference python2 instead of python3.

**Comment by derhelge** [comment]
Hi Adam,

> We should tag master and do a proper release. 

Sorry if i missed it... But can you do it if its not that much work to do? I guess its more easy to rely on a tag to rebuild the distro-packages.

Thanks for your work! :+1:

**Comment by GrantEdwards** [comment]
rabbitvcs 0.17 (for svn users) can no longer be installed on Gentoo without significant extra work.  The Gentoo pysvn package now only supports Python 3.6.

**Comment by adamplumb** [comment]
I've tagged v0.18 now.
