### ISSUE TITLE
Commit log line spacing

### ISSUE THREAD

**Issue by coppolat1** [rabbitvcs/rabbitvcs#280]
I'm using rabbitvcs on CentOS 7.7 using Nemo 3.6.5, something I'm noticing is the strange line spacing in the commit dialog. It looks like the line spacing is set to something like 1.5x which I think is strange for plain text this type of development tool.

If someone could point me in the right direction to change this, or explain to me if this was done intentionally, I would appreciate it. 

rabbitvcs noob here, i'm merely a user of this  tool so I'm not sure if this is issue is 
particular to the Nemo client or something within rabbitvcs itself.

Thanks.

![rabbitvcslinespacing](https://user-images.githubusercontent.com/22183805/66755687-83fd4800-ee66-11e9-9c3f-d86c27d3b923.png)

**Comment by monnerat** [comment]
Thanks for your report: this is now pushed in master.
