### ISSUE TITLE
How do you run rabbitvcs after 'python setup.py install --user' ?

### ISSUE THREAD

**Issue by GrantEdwards** [rabbitvcs/rabbitvcs#287]
I've installed 0.18 with the command

  $ python setup.py install --user

Everything seems to have installed without any errors or warnings in the usual place [~/local/lib64/python3.6/site-packages/], but I can't figure out how to actually run rabbitvcs (preferably from the comand line).

How do I invoke rabbitvcs?

**Comment by adamplumb** [comment]
You'll need to install clients. You could install the Nautilus plugin or
the cli client for example.
