### ISSUE TITLE
Default log limit of 100 is taking long time to load on svn

### ISSUE THREAD

**Issue by ixevix** [rabbitvcs/rabbitvcs#291]
The "Show Log" functionality works great with git but when trying to log the latest 100 entries over svn it takes longer than 10 seconds. Please lower the limit to say 10 for svn.

**Comment by monnerat** [comment]
Subversion log accesses the server while git log does not. This explains the longer delay.
That said, I tried on a sourceforge repo and it takes less than 2 secs for 100 records and ~8 secs for 500, which seems acceptable.
