### ISSUE TITLE
rabbitvcs and thunar

### ISSUE THREAD

**Issue by gilcu3** [rabbitvcs/rabbitvcs#294]
Something weird is happening with rabbitcvs and thunar after some recent update. All features work except that no emblems appear in folders and files. I tried looking at the logs but nothing shows. DO you have any clue?

thunar 1.8.14
rabbitvcs 0.18.0
python-thunarx 1:0.5.1
Python 3.8.2

**Comment by adamplumb** [comment]
Thunar has never been able to put emblems on folders and files as far as I
can remember.  Have you seen otherwise?

**Comment by gilcu3** [comment]
Oh yes now I remember sorry.. and I spent 4 hours yesterday trying to debug it.
