### ISSUE TITLE
TypeError: Don't know which D-Bus type to use to encode type "NoneType"

### ISSUE THREAD

**Issue by metal450** [rabbitvcs/rabbitvcs#295]
Trying to use the nemo client running on KDE Plasma 5, it's failing with the following message (when I nemo -q in a terminal):

```
ERROR:dbus.connection:Unable to set arguments (None, None) according to signature None: <class 'TypeError'>: Don't know which D-Bus type to use to encode type "NoneType"
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/RabbitVCS.py", line 217, in __init__
    self.status_checker = StatusChecker()
  File "/usr/lib/python3/dist-packages/rabbitvcs/services/checkerservice.py", line 258, in __init__
    self._connect_to_checker()
  File "/usr/lib/python3/dist-packages/rabbitvcs/services/checkerservice.py", line 270, in _connect_to_checker
    self.status_checker.SetLocale(*locale.getlocale(locale.LC_MESSAGES))
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
TypeError: Don't know which D-Bus type to use to encode type "NoneType"

```

Install is being performed per the instructions here: https://github.com/rabbitvcs/rabbitvcs/issues/251#issuecomment-515971964

It works when nemo is run under Cinnamon desktop environment - but not when run under KDE. In other words, it's the exact same system - if I boot into Cinnamon & launch Nemo, RabbitVCS is fully functional. If I boot into KDE & launch nemo, I get the error above.

**Comment by monnerat** [comment]
Thanks for the bug report.
Commit 5a06fdb should fix this issue.
Please try from current master and report here. Thanks in advance.

**Comment by metal450** [comment]
I'm no longer using Nemo - however, using Nautilus on Kubuntu had a similar bug, which I ended up fixing per #297 (after many changes to the install instructions)

**Comment by monnerat** [comment]
Thanks for the feedback. This commit should also fix the bug in other (i.e.: non-nemo) contexts.
Closing issue. If the prblem persists, please reopen.
