### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'True'

### ISSUE THREAD

**Issue by gabrielfin** [rabbitvcs/rabbitvcs#299]
The settings dialog doesn't open, and the following error shows up:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/ui/settings.py", line 417, in <module>
    window = Settings(options.base_dir)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/ui/settings.py", line 89, in __init__
    int(self.settings.get("general","enable_highlighting"))
ValueError: invalid literal for int() with base 10: 'True'
```
Apparently the setting is stored as a `boolean` but the code expects an `int`.

I'm using v0.18

**Comment by monnerat** [comment]
The value is expected to be returned as a bool, not a string. Since this is a new option, I suspect your installation is loading an old leftover configspec.ini file. That could be the cause of the problem. Please check the 0.18 version of configspec.ini is installed and properly loaded.

**Comment by gabrielfin** [comment]
Indeed. There was an old one in `/usr/lib/python2.7/dist-packages/rabbitvcs/util/configspec/configspec.ini`

A while ago, I may have "updated" rabbitvcs by replacing the `/usr/lib/python2.7/dist-packages/rabbitvcs` folder, which leaves files from the source that should not actually be installed :s 

Moral of the story: always run the installer

Thanks for the help!

**Comment by monnerat** [comment]
> Thanks for the help!

You're welcome!
Thanks to you for the feedback.
