### ISSUE TITLE
Configuration: Only use rabbitvcs for certain formats.

### ISSUE THREAD

**Issue by TurkeyMan** [rabbitvcs/rabbitvcs#3]
I use TortoiseHg for Mercurial, and RabbitVCS for everything else. Currently, when I right-click on a hg repo, the context menu is populated by both tortoise and rabbit options, and 2 sets of icons on all the hg files.
I would like to disable RabbitVCS for only hg repos.

**Comment by adamplumb** [comment]
I'm going to close this one out because I've deprecated mercurial support, but I also added a settings mechanism to enable or disable svn/git.
