### ISSUE TITLE
Conflict editing doesn't work in SVN

### ISSUE THREAD

**Issue by gabrielfin** [rabbitvcs/rabbitvcs#300]
When merging a branch in SVN and a conflict occurs, the following error shows up:

```
(RabbitVCS:13122): Gtk-CRITICAL **: 19:50:42.395: gtk_main_quit: assertion 'main_loops != NULL' failed
```
And the window showing the merging status never completes the merging.

And there's a process runing that remains "stuck" and has to be killed:
```
python /usr/lib/python2.7/dist-packages/rabbitvcs/ui/editconflicts.py --name RabbitVCS /path/to/conflicted/file
```

I'm using v0.18

**Comment by monnerat** [comment]
Thanks for the bug report.
Commit fdba1dd should fix it. If the problem persists, please reopen.
