### ISSUE TITLE
Log window - scrolling w/ arrow keys does not update the UI

### ISSUE THREAD

**Issue by metal450** [rabbitvcs/rabbitvcs#307]
If I bring up the commit log & use the arrow keys to scroll up & down though the list of commits, the 'message' and 'affected files' parts of the window do not update.  The only way to get them to update is to take the mouse and physically click on that line in the list.

Running Kubuntu 20.04, KDE Plasma 5.18.5.  Latest version of rabbitvcs via code checkout 5 minutes prior to posting this ticket (i.e. not installed from apt - installed directly from source).

**Comment by AlexFolland** [comment]
I see this also in Manjaro 20.1.1 running Nemo 4.6.5 when browsing an SVN log.  The "About RabbitVCS" menu says:

- "0.18.0"
- "Subversion - 1.14.0"
- "Pysvn - 1.9.12.0"
- "ConfigObj - 5.0.6".

For comparison with TortoiseSVN, which I've heard that matching functionality is the goal of RabbitVCS, navigating the log with arrowkeys is working well in the TortoiseSVN log viewer in Windows 7 64-bit.
