### ISSUE TITLE
SVN credentials not stored

### ISSUE THREAD

**Issue by pczekalski** [rabbitvcs/rabbitvcs#310]
Whatever I do, I can not save credentials used to connect to my SVN server. 
Checking "Save Authentication" checkbox in the Nautilus-SVN integration does not work.
The OS is Ubuntu 20.04, RabbitVCS 0.18.

Regards,

P.
![Screenshot from 2020-07-19 17-58-03](https://user-images.githubusercontent.com/23726790/87879236-ce10ec80-c9e9-11ea-9187-3ec6011c287e.png)

**Comment by F23ko** [comment]
Ubuntu 20.04, RabbitVCS 0.18. svn, version 1.13.0
same problem

https://github.com/rabbitvcs/rabbitvcs/issues/270

I thought svn didn't storage password in plain text.

I saw diffent in my  .subversion/auth/svn.simple
( with rabbitvcs )
svn:realmstring

( with cml )
passtype
gnome-keyring

**Comment by andrsmllr** [comment]
Same here. Very annoying when having to use RabbitVCS on a daily basis.
Also Ubuntu 20.04 (Focal), RabbitVCS 0.18, svn 1.13.0 (r1867053)

**Comment by dtrunk90** [comment]
Take a look here: https://github.com/rabbitvcs/rabbitvcs/issues/270#issuecomment-619424378_
Upgrading pysvn to 1.9.11 works. This is not an rabbitvcs issue. Instead it was an python3-svn issue.

**Comment by andrsmllr** [comment]
@dtrunk90 Thanks that actually solved my problem.

**Comment by pczekalski** [comment]
Thanks, that actually helped!

**Comment by Leanderlau** [comment]
solved

**Comment by codeloopy** [comment]
@andrsmllr Thank you!
