### ISSUE TITLE
Resetting not working

### ISSUE THREAD

**Issue by ddobrev** [rabbitvcs/rabbitvcs#319]
When I attempt to reset my repository, I always get the same message: "Cannot do hard reset with paths".
0.18-1ubuntu1 on Kubuntu 20.04.

**Comment by ddobrev** [comment]
Hello, almost a month has passed with no reply. [Other issues](https://github.com/rabbitvcs/rabbitvcs/issues/308) are almost half a year old with no reply either. If this project's dead, please say so in order for us to find alternatives.

**Comment by Shambler0** [comment]
> When I attempt to reset my repository, I always get the same message: "Cannot do hard reset with paths". 0.18-1ubuntu1 on Kubuntu 20.04.

I was searching for this error and found your issue

This appears to be a fork, main repo is:
https://github.com/rabbitvcs/rabbitvcs

Anyway, if you still need resetting, the solution is:

open file:
/usr/lib/python3/dist-packages/rabbitvcs/vcs/git/gittyup/command.py 
(or whereever rabbitvcs it is installed)

find function:
`    def reset(self, path, revision, type=None):   `

replace line:
`        if relative_path:`

with (mind the exact spacing before the code line):
`        if relative_path and not "soft" == type and not "hard" == type:`

this disables paths (entire repo is reset) for hard and soft reset which are the ones I find useful
