### ISSUE TITLE
How to open log viewer GUI without nautilus?

### ISSUE THREAD

**Issue by Mingun** [rabbitvcs/rabbitvcs#322]
How to open GUI from a command line (especially this window: http://wiki.rabbitvcs.org/wiki/_detail/about/log_viewer.png?id=about%3Ascreenshots)?

Nautilus integration not working for me, I just haven't RabbitVCS menu and anyway, I hardly ever use nautilus itself.

**Comment by Mingun** [comment]
At least I found, that nautilus integration just worked very slowly -- perhaps due to #76 (I have a ~5.5GB git repository).

**Comment by adamplumb** [comment]
If you have the cli tools installed (rabbitvcs-cli client) then you should
be able to type rabbitvcs log in the folder.

**Comment by Mingun** [comment]
Thanks, that works (but not in the `git worktree` directory -- #323)!
