### ISSUE TITLE
Extra character in URL when using compare

### ISSUE THREAD

**Issue by hschmith** [rabbitvcs/rabbitvcs#335]
When using the "compare" functionality rabbitvcs seems to add an extra 'b' character into the URL for the first file to compare. Viewing the log table of any SVN-controlled file and selecting any two revisions and then "Compare revisions" I get the following error message:

`Illegal repository URL 'b'https://<SERVER>/<REPO>/trunk/.../<FILE>''`

The comparison tool (meld in my case) opens, but the file with the smaller revision number is missing. The one with the higher revision number shows up as expected.

The error occurs on the following system:
Ubuntu 20.04.2 LTS
GNOME Files 3.36.3-stable
RabbitVCS 0.18
Subversion - 1.13.0
Pysvn - 1.9.9.0
ConfigObj - 5.0.6

**Comment by mskrzypczak** [comment]
Affects me too as well. Please do something about it, it seems to be some trivial bug.

**Comment by damsma** [comment]
https://github.com/rabbitvcs/rabbitvcs/issues/338#issuecomment-1319876181
