### ISSUE TITLE
compare revisions in Log window not possible (svn)

### ISSUE THREAD

**Issue by cmarhoff** [rabbitvcs/rabbitvcs#338]
I use ubuntu 20.04 and installed subversion, sqlite3, and rabbitvcs-nautilus according to your documentation.
Then I imported a database created with tortoisesvn and the underlying local svnserver for windows.
Many things look very good, like Log, comparing with base, etc.
But when I open a Log window for a file and attempt to compare  two revisions (mark two revs, then "Compare revisions" from the context menu), an error pops up :
 "Illegale Projektarchiv-URL »b'svn://localhost/gw/trunk/gw/main.c"
and when "OK"ing this, the left panel of Meld remains empty, just another error message:
"There was a problem opening the file “/tmp/rabbitvcs-02e898289e/rabbitvcs-1-2917-main.c'”."
and in fact this file in /tmp/ does not exist (whereas the corresponding file for the right panel exists)

I repeated all that with manually installed newest version from git (instead using apt), same outcome.

I even converted (although not perfectly) my subversion database to git and tested here, and here the "compare revs" in Log window actually works fine! But I do not want git.

**Comment by damsma** [comment]
Working as of today with the newest revision:

`mkdir /rabbitvcs_svn
cd /rabbitvcs_svn
git clone https://github.com/rabbitvcs/rabbitvcs.git

cd /usr/lib/python3/dist-packages/rabbitvcs
cp -R /rabbitvcs_svn/rabbitvcs/rabbitvcs/* .
`

**Comment by cmarhoff** [comment]
it worked! thank you so much!
