### ISSUE TITLE
Copied from information not displayed

### ISSUE THREAD

**Issue by KiAchim** [rabbitvcs/rabbitvcs#340]
The 'show log' dialogues do not show the full copy source information. They do show the revision number of the source of the copy but not the source path. 
I'm running Rabbit vcs on 
System:    Kernel: 5.13.0-21-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.0.7 
           wm: muffin dm: LightDM  Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 
Rabbitvcs-core 4.4 Version 0.18-1ubuntu1
![Auswahl_122](https://user-images.githubusercontent.com/61900737/146335187-07921308-f5b3-4fd1-b57c-acd6e237fc5c.jpg)
![Auswahl_121](https://user-images.githubusercontent.com/61900737/146335195-3a223f3f-f0c7-42c5-8e39-26fe75d78156.jpg)
![Auswahl_120](https://user-images.githubusercontent.com/61900737/146335200-74e495d6-def1-445f-ad8d-f00287693c8c.jpg)

Rabbitvcs-nautilus 4.2 Version 0.18-1ubuntu1

**Comment by JorisHansMeijer** [comment]
Pullrequest #378 should solve this issue.
