### ISSUE TITLE
Mercurial support

### ISSUE THREAD

**Issue by dimonomid** [rabbitvcs/rabbitvcs#35]
Hi,
It would be really great if RabbitVCS supports Mercurial VCS. Do you have plans to implement it?

**Comment by adamplumb** [comment]
There was basic support for statuses put in at one point but it's a lot of work to implement the rest of it and I don't think there's enough interest.  I haven't used mercurial for anything in years so I'm not really keen on it myself.  But if someone is interested I'd be glad to help steer them in the right directions.
