### ISSUE TITLE
New Release for Ubuntu 20.04 with latest bugfixes

### ISSUE THREAD

**Issue by Megamouse** [rabbitvcs/rabbitvcs#350]
Hi, this project is really speeding up my svn workflow.
But there are a couple of bugs in Ubuntu 20.04 in the v0.18 release that cause me to manually copy over the files of the newest commit whenever I setup a new system.

Since Ubuntu 22.04 is now released, would it be possible to release a v0.19 for us 20.04 users?
This would make life so much easier.

**Comment by philippun1** [comment]
Version 0.19 has been released.
