### ISSUE TITLE
Cannot view Git-Log in rabbitvcs-nautilus

### ISSUE THREAD

**Issue by OliTat** [rabbitvcs/rabbitvcs#370]
If the Git-Log would be opened by any action like:
Opening the log directly
Choosing a revision for diff-comparison
Choosing a revision for merging

A Message field called "Message" opens and the log loads indefinetly.

Opening the log with rabbitvcs-cli yields the error message:

> 
> ERROR	rabbitvcs.util.__init__	
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/rabbitvcs/util/__init__.py", line 120, in start
>     func.start()
>   File "/usr/lib/python3/dist-packages/rabbitvcs/util/__init__.py", line 45, in start
>     self.result = self.func(*self.args, **self.kwargs)
>   File "/usr/lib/python3/dist-packages/rabbitvcs/vcs/git/__init__.py", line 775, in log
>     items = self.client.log(path, skip, limit, revision.primitive(), showtype)
>   File "/usr/lib/python3/dist-packages/rabbitvcs/vcs/git/gittyup/client.py", line 1643, in log
>     del revision["message"]
> KeyError: 'message'
> ERROR	rabbitvcs.ui.action	'message'
> NoneType: None

rabbitvcs has been completely removed and reinstalled, the error persists.
The problem exists in different repositories.

Using Nautilus 42.2

**Comment by philippun1** [comment]
What version of rabbitvcs? How did you (re)install it?

What distro?

Does it happen with every repo or just a specific one?

**Comment by philippun1** [comment]
I was able to reproduce it, it only happens if there is an empty commit message in log. Fixed with https://github.com/rabbitvcs/rabbitvcs/commit/77ea970a98b37e43690f4e8a2703ebc56b94124d.
