### ISSUE TITLE
RabbitVCS on RHEL8 installation issue

### ISSUE THREAD

**Issue by alunajin** [rabbitvcs/rabbitvcs#375]
I was unable to install RabbitVCS on a RHEL8 server. I'm getting the following error:

_[root@test-srv yum.repos.d]# yum install rabbitvcs*
Updating Subscription Management repositories.
Last metadata expiration check: 0:33:21 ago on Mon 17 Apr 2023 03:19:12 PM PDT.
No match for argument: rabbitvcs*
Error: Unable to find a match: rabbitvcs*_

Any insights will be appreciated. I reached out to RedHat Support but they were unable to provide me with any solution or explanation.

**Comment by vitlav** [comment]
RabbitVCS is a GUI program for developers. It is seems RHEL is not intendend be a developer platform. Just use Fedora.

**Comment by paolofrs** [comment]
I was able to install on a Centos 8 Stream (if I am not wrong is the last available downstream of RHEL 8). 

Just follow the manual installation. It helps adding the EPEL repository. If some packets are anyway missing in the repository, you can manually download them from internet. Just google them.

**Comment by philippun1** [comment]
It looks like the package does not exist on RHEL8. But this is a packaging issue on Red Hat side.
