### ISSUE TITLE
No context menu on Ubuntu 23.04

### ISSUE THREAD

**Issue by ssarna1** [rabbitvcs/rabbitvcs#377]
There is no context menu after upgrade from 22.04 
when trying to install rabbitvcs-nautilus :
package 'rabbitvcs-nautilus' has no installation candidate

Thanks in advance for any help

**Comment by ssarna1** [comment]
Is there any way to install nautilus package from jammy release? Would it work on 23.04?

**Comment by ssarna1** [comment]
> Currently the only option is to install it manually as a whole.

Can You elaborate on that? Pretend i know nothing about Linux.

**Comment by philippun1** [comment]
> Can You elaborate on that? Pretend i know nothing about Linux.

Basically you have to get the sources from github and run this command inside the main folder: `sudo python setup.py install`

There are detailed instructions in the README.md of this repo.

**Comment by ssarna1** [comment]
That did not work. As in Readme, i run 
`# python setup.py install --install-layout=deb`
and copied Nautilus "RabbitVCS.py" into `/usr/share/nautilus-python/extensions`
but there is no change.

**Comment by ssarna1** [comment]
I must have messed something up earlier, did it again and rebooted and it works.
Thanks!
