### ISSUE TITLE
Bugfix version 0.19

### ISSUE THREAD

**Issue by philippun1** [rabbitvcs/rabbitvcs#380]
Hello,

I would like to make a version 0.19 with as many bug fixes as possible before the gtk4 migration happens. This might also benefit the Debian/Ubuntu packages, which are currently lacking the Nautilus plugin.

As I personally only work on Ubuntu/Manjaro with Gnome and Nautilus plugin, help with testing the other plugins and distributions would be welcome.

There are also plenty of issues open, to track which one are still relevant I created a v0.19 milestone. If a bug is relevant, it can be added to the milestone.

**Comment by philippun1** [comment]
I did some testing on various distros (Ubuntu 22.04/23.04, Ubuntu MATE, Linux Mint, Manjaro), not everything in detail but some common workflows. I reviewed and merged relevant MRs and also did some bug fixing.

In my opinion we are good to go!

@CloCkWeRX What do you think? I don't know the procedure, can I just tag the version and create a release?

**Comment by CloCkWeRX** [comment]
Digging through older docs:
http://wiki.rabbitvcs.org/wiki/development/packaging

This may be of some assistance.

**Comment by philippun1** [comment]
Ok, thanks. I released v0.19.
