### ISSUE TITLE
No emblems in Nautilus 3 after installing from source

### ISSUE THREAD

**Issue by lofidevops** [rabbitvcs/rabbitvcs#45]
I have installed RabbitVCS and the Nautilus 3 client from source using the up-to-date Ubuntu instructions (using `--install-layout=deb` and updated locations). After installing, RabbitVCS appears in the Nautilus context menu, but folders do not get RabbitVCS emblems.

Notes:
- Persists after logout/login and restarting machine.
- Happens on 0.16.0 branch and trunk branch.
- I have confirmed that /usr/share/icons/hicolor/scalable/emblems contains the emblem files.

Any suggestions for next place to look?

**Comment by jesponde** [comment]
For those still having problems installing RabbitVCS from source, here is my installation steps:
```bash
# Install prerequisites
$ sudo apt-get install python-tk python-gtk2 python-configobj python-gobject  python-simplejson  python-gtkspell  python-svn  subversion python-dulwich git meld

# Fetch source code
$ git clone https://github.com/rabbitvcs/rabbitvcs.git

# Install RabbitVCS
$ cd rabbitvcs
$ sudo python setup.py install --install-layout=deb

# Install Nautilus 3 extension
$ sudo mkdir -p ~/.local/share/nautilus-python/extensions
$ cp clients/nautilus-3.0/RabbitVCS.py ~/.local/share/nautilus-python/extensions
$ sudo mkdir -p ~/.icons
$ cp -r data/icons/hicolor ~/.icons

# Restart Nautilus
$ nautilus -q
$ pgrep -f checkerservice.pyc | xargs kill
$ nohup nautilus > /dev/null &
```
