### ISSUE TITLE
Rabbit dialogs hang on Ubuntu 14.04

### ISSUE THREAD

**Issue by smouzakitis** [rabbitvcs/rabbitvcs#52]
Hi i am using ubuntu 14.04 and installed RabbitVCS.

I have setup a git repository. In many dialogs (e.g. Update command or the Commit after you choose some files) the dialog hangs out completely, therefore nothing really works.

The rabbitvcs.log file does not show any error. 

any clues?

**Comment by CloCkWeRX** [comment]
Not enough info for us to go on I'm afraid. Going to assume it's #21
