### ISSUE TITLE
[query] How can I investigate a RabbitVCS slowdown?

### ISSUE THREAD

**Issue by kwill** [rabbitvcs/rabbitvcs#55]
I have a reproducible issue that seems to trigger a RabbitVCS slowdown. Specifically, when I open a specific folder in Nautilus (that contains several SVN repos), a slowdown occurs (but no crashes).

Is there a general approach I can take to investigate this slowdown? What is a meaningful way to "size" the repos (in case that's related to the issue)?

I'm running 0.16 from source, so I'm hoping there's a debug package I can activate, or some decorators I can sprinkle in.

----

For reference, the slowdown sequence is:

 * Open folder, system immediately starts slowing down (frex, slow to switch between applications), icons within folder not visible
 * Opening `top` in a TTY reveals nothing out of the ordinary (all processes below 2% CPU, Python and Nautilus do not appear near the top of the list)
 * After 5-10 secs, Nautilus window goes grey
 * After 30-60 secs, Nautilus window back to normal, folder icons appear (with clock emblem), Python process (I'm assuming RabbitVCS) now using approx 40% CPU - remains this way for at least 5 mins, system now usable but still slow
 * Clicking on one of the folders (repo root folders) repeats the process

The folders in question are on an encfs mount, and encfs CPU usage increases at the same time as Python, but:

 * I'm quite confident this was happening before I switched to encfs
 * this doesn't happen with other (Git) repos on encfs

**Comment by CloCkWeRX** [comment]
Closing off in favour of #76
