### ISSUE TITLE
If possible a source code widget should be embedded in the Blame viewer so syntax highlighting is available

### ISSUE THREAD

**Issue by agroszer** [rabbitvcs/rabbitvcs#6]
Taken from http://code.google.com/p/rabbitvcs/issues/detail?id=38

TortoiseSVN blame is definitely the killer, with the revision coloring, and right click -> blame previous revision: http://tortoisesvn.tigris.org/blame.html

Or git gui blame...

This is a mockup from g-code no 38:
![blame-with-embedded-sourcecode-viewer](https://f.cloud.github.com/assets/350912/2319299/b468ab84-a37a-11e3-9da4-43345586a7aa.png)

**Comment by monnerat** [comment]
Commit 564d777 introduces syntax highlighting in the annotate dialog providing the pygments library is installed. GtkSourceView is not needed. Please clone and install from the latest master branch for testing. Reopen this issue if you have problems with syntax hightlighting. Thanks.
