### ISSUE TITLE
Unable to create new folder in root folder

### ISSUE THREAD

**Issue by anno0** [rabbitvcs/rabbitvcs#68]
In RabbitVCS it is impossible to create a new folder in root folder because each entry in the repository browser is listed as a sub folder. 

There is no free space e.g. it can be found in every file manager or Tortoise SVN /Git. So if I press right mouse button to open context menu and to create a new folder it is not possible.

**Comment by monnerat** [comment]
Fixed in https://github.com/rabbitvcs/rabbitvcs/commit/154d4c4d268b348e63ddd4f64b6fe1cc940221f6
Closing.
