### ISSUE TITLE
Python error hangs Thunar (rabbitvcs 0.16, Xubuntu 14.04) - have resolution

### ISSUE THREAD

**Issue by grahambartlett** [rabbitvcs/rabbitvcs#69]
I've just installed RabbitVCS on Xubuntu 14.04 according to the instructions.  Added PPA, and installed rabbitvs-cli, thunar-vcs-plugin and rabbitvcs-thunar (in that order), then rebooted.

Running Thunar, I now get the following set of Python errors immediately, and Thunar hangs:-
```
(thunar:3571): thunarx-python-WARNING **: g_module_open libpython failed: /usr/lib/libpython2.7.so.1.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gobject/__init__.py", line 24, in <module>
    import sys
  File "/usr/lib/python2.7/dist-packages/gobject/__init__.py", line 26, in <module>
    from glib import spawn_async, idle_add, timeout_add, timeout_add_seconds, \
  File "/usr/lib/python2.7/dist-packages/glib/__init__.py", line 22, in <module>
    from glib._glib import *
ImportError: /usr/lib/libpyglib-2.0-python2.7.so.0: undefined symbol: _Py_ZeroStruct

(thunar:3571): thunarx-python-WARNING **: could not import gobject

(thunar:3571): thunarx-python-WARNING **: pygobject initialization failed

(thunar:3571): thunarx-python-WARNING **: thunarx_python_init_python failed
Traceback (most recent call last):
  File "/usr/share/thunarx-python/extensions/RabbitVCS.py", line 31, in <module>
    import datetime
ImportError: /usr/lib/python2.7/lib-dynload/datetime.i386-linux-gnu.so: undefined symbol: PyExc_SystemError
```
By googling parts of this, I found the solution.  It's an old bug from 18 months ago which apparently still isn't resolved, and got lost in the shuffle in the move to Github.
https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1157246

Running
sudo ln -sf /usr/lib/i386-linux-gnu/libpython2.7.so.1 /usr/lib/libpython2.7.so.1.0
has apparently fixed the problem.  Note that I'm on 32-bit (because I'm running this in a VM); I guess replace "i386" with "x86_64" for a 64-bit system.

**Comment by CloCkWeRX** [comment]
https://bugs.launchpad.net/ubuntu/+source/nautilus-python/+bug/1170017 is the main issue, and it's marked as fixed released.
