### ISSUE TITLE
Export fail

### ISSUE THREAD

**Issue by FrauJaja** [rabbitvcs/rabbitvcs#70]
I wanted to export my working directory in order to remove it from version control. Unfortunately, when I had to choose the destination, I made a mistake:

URL: /home/hannah/svn-workspace/folder1
Destination: /home/hannah/Desktop

I guess the correct destination would have been "home/hannah/Desktop/folder1"...? After exporting suddenly my desktop was completely empty. The search cannot find the files that were on the desktop before. But the exported content from "folder1" is not on the desktop either. How does export work, what happened, and can I somehow get the lost files back to my Desktop?

**Comment by zabby16546** [comment]
I had the same issue. Went to export files to my Desktop for a programming assignment, instead it deleted my Desktop. Do you guys think TestDisk can be used to recover the files, or are they long gone?

**Comment by detly** [comment]
There's a decent chance TestDisk/PhotoRec will work. Use another computer
to do it, of course, and mount the disc read only. In fact, for data
recovery I prefer to use dd to take an image of the disc/partition and
operate on that.

**Comment by cmcinroy** [comment]
That's a great suggestion, detly.  Thank you.

**Comment by zabby16546** [comment]
I actually didn't know about PhotoRec until you posted about it, so I went and gave it a look. It recovered my files flawlessly. Thanks for the suggestion! Your tip about making an image and recovering from that was also quite helpful. As for the issue with the checkout, is that due to anything in particular? Should I reinstall rabbitvcs, or is the fault within the program?

**Comment by detly** [comment]
It is a bug in RabbitVCS. But I don't work on the software itself any more,
only the packaging, so there's not a lot I can do about it myself :/

**Comment by zabby16546** [comment]
Okay, well I appreciate the feedback. Good luck guys!

**Comment by CloCkWeRX** [comment]
Fixed by #89
