### ISSUE TITLE
Sparse checkout

### ISSUE THREAD

**Issue by jehon** [rabbitvcs/rabbitvcs#74]
Since subversion 1.5, it is possible to have a sparse checkout, i.e. a partial checkout (cfr. http://svnbook.red-bean.com/en/1.7/svn.advanced.sparsedirs.html).

To do that, you usually choose wich folder you want to checkout.

This is really usefull when using very big repositories.

Do you plan to implement that in a close future?

**Comment by CloCkWeRX** [comment]
Patches welcome to do this, but no plans on our part.

**Comment by jehon** [comment]
Not needed anymore from me.

Thanks
