### ISSUE TITLE
No emblems on Fedora 20/21

### ISSUE THREAD

**Issue by az-z** [rabbitvcs/rabbitvcs#75]
hello,
 i run fedora 20, x64, XFCE with Thunar 1.6.3.
packages are :
rabbitvcs-thunar-0.16-1.fc20.x86_64
rabbitvcs-core-0.16-1.fc20.noarch

i do not have any emblems on the files and directories under git managment.
I ran wiki suggested workaround - http://wiki.rabbitvcs.org/wiki/support/faq#troubleshooting - 
"        If the context menu items are showing up but not the emblems or icons, then you may need to update your icon cache via the command: “gtk-update-icon-cache -f /usr/share/icons/hicolor” as root.
"
but that made no difference.
Please advise.

**Comment by az-z** [comment]
since opening the bug i moved to F21. Still this app is not working right:
[code]
[az@toshiba ~]$ uname -a
Linux toshiba 3.18.3-201.local.fc21.x86_64 #1 SMP Wed Jan 28 22:08:05 EST 2015 x86_64 x86_64 x86_64 GNU/Linux
[az@toshiba ~]$ cat /etc/redhat-release 
Fedora release 21 (Twenty One)
[az@toshiba ~]$ rpm -qa | grep rabit*
^C
[az@toshiba ~]$ rpm -qa | grep rabbit*
rabbitvcs-core-0.16-3.fc21.noarch
rabbitvcs-thunar-0.16-3.fc21.x86_64
[/code]

**Comment by CloCkWeRX** [comment]
I recommend you report this to Fedora as a packaging issue, and link back to here.

**Comment by Xylemon** [comment]
I do not see any emblems with Thunar on Arch either nor did I on Slackware. I do not believe this is a packaging fault.
