### ISSUE TITLE
Cannot checkout using git

### ISSUE THREAD

**Issue by nrobertson2** [rabbitvcs/rabbitvcs#77]
I can checkout using a different client (but I don't like the other client and it glitched and deleted all the .git files).

The url structure is ssh://username@ipaddress:port/path

Please fix this, it will make me very happy. :).

Additional info I have to use a vpn for authentication.

**Comment by CloCkWeRX** [comment]
Are there any error logs you can provide?

**Comment by adamplumb** [comment]
This should be fixed on master now.
