### ISSUE TITLE
Rabbit vcs Commit is not working on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by SelvamaniD** [rabbitvcs/rabbitvcs#81]
On click on project folder , when i click commit , the modal dialog is not appearing. 
Same issue is obeserverd with update, diff& checkout also but when i click settings, it is open Modal dialog.

**Comment by fuesika** [comment]
Ubuntu 11.04 had its official end-of-life on October 28, 2012. The official ubuntu repositories even do not provide any more information about which release was used back then. Please update to the latest Ubuntu --possibly a LTS release-- and check if this failure is reproducible.

@CloCkWeRX: I propose to close this issue.

**Comment by SelvamaniD** [comment]
There real problem i am facing here 
Popup windows don't appear after clicking on RabbitVCS menu items in Nautilus

**Comment by CloCkWeRX** [comment]
Try running the commands from bash (rabbitvcs log) in your repository, it'll probably produce more informative feedback. Until then...
