### ISSUE TITLE
Rabbit VCS don't commit

### ISSUE THREAD

**Issue by bastri** [rabbitvcs/rabbitvcs#82]
Hi

I can update but I can't commit. When I commit I receive this error (After a few minutes of waiting in vain):

" Modified /home/normal/Desktop/Yrigoyen/Presupuesto.xlsx None 
Changed /home/normal/Desktop/Yrigoyen/Presupuesto.xlsx None Commit failed (details follow): Server sent unexpected return value (500 Internal Server Error) in response to PUT request for '/svn/yrigoyen/!svn/wrk/a2ad0d7d-b6c2-48f2-bf1b-88ea21949798/Presupuesto.xlsx'
Finished "

I am using Debian 7.8 x64, and the lastest rabbitvcs version installed from tarball.

What can I do?

PD: Sorry for my basic english.

**Comment by CloCkWeRX** [comment]
Check your SVN server logs - a HTTP 500 server error isn't something we can fix in a client application
