### ISSUE TITLE
Show unversioned files checkbox in Commit dialog does the exact opposite

### ISSUE THREAD

**Issue by bulkware** [rabbitvcs/rabbitvcs#83]
Show unversioned files checkbox in Commit dialog does the exact opposite. When it's not checked, it shows the unversioned files.

Versions:
Kernel: 3.13.0-37-generic x86_64 (64 bit)
Desktop: Gnome
Distro: Linux Mint 17.1 Rebecca
nemo: 2.4.5
Python - 2.7.6
RabbitVCS - 0.16.0
Subversion - 1.8.8.
Pysvn - 1.7.8.0
ConfigObj - 4.7.2

Language:
en_US.UTF-8

I am happy to provide more information about this problem. Just tell me how I can help.

**Comment by rnyberg** [comment]
I can verify. (Ubuntu 14.04)

**Comment by CloCkWeRX** [comment]
#71

**Comment by andreldm** [comment]
Please make a release in order to users get this and lots of others fixes.
