### ISSUE TITLE
RabbitVCS commit problem

### ISSUE THREAD

**Issue by bastri** [rabbitvcs/rabbitvcs#85]
Hi. I install RabbitVCS in Debian 7.8 x64 using this command:
$  apt-get install rabbitvcs-core rabbitvcs-nautilus rabbitvcs-gedit rabbitvcs-cli

I opened nautilus from gnome-terminal, then (With the options in context menu of right click) I realized a checkout, and when I want to commit nothing happens. But in the terminal I recive this error:

![screenshot from 2015-02-24 09 22 42](https://cloud.githubusercontent.com/assets/10988337/6349206/c9f25478-bc06-11e4-8a15-32a56e20db5b.png)

What can I do? Thanks a lot. 

PD: Sorry for my basic english

**Comment by CloCkWeRX** [comment]
I suspect the configuration doesn't have
```
[general]
language = string(default="English")
enable_attributes = boolean(default=True)
enable_emblems = boolean(default=True)
enable_recursive = boolean(default=True)
show_debug = boolean(default=False)
show_unversioned_files = boolean(default=True)
```

in there properly - and nautilus is being started in a funny directory, so it doesn't know where to go find it.

I recommend you file a bug in the debian bug tracker and cross link it to here, if it's a packaging issue on our part; and re-open this one.
