### ISSUE TITLE
Commit problem(`/usr/bin/python': double free or corruption)

### ISSUE THREAD

**Issue by boris4manutd** [rabbitvcs/rabbitvcs#87]
Hello,
I'm using rabbitvcs on Ubuntu 14.04.2 LTS, and I'm having problems with with commits, to be precise with first commit, which is in my case folder structure(docs,branches,tags, trunk [with existing data, it is not large amount of data, but there is a lot of pictures and always some .php, .css, .js files]). 
As u can see I'm web developer.
So during that "first" commit, I add files, folders, click commit, commit starts, but it goes for let say one third of process(or less) and stops instantly. After that I need to run cleanup of repo and start again, with same resoult. I can replace that first and large by spliting that commit to several small ones, but that is frustrating and time consuming.
So after some research I found config file of rabbitvcs(/usr/share/rabbitvcs/configspec.ini) and changed show_debug = boolean(default=False) => show_debug = boolean(default=True).
After that I run via termianal rabbitvcs commit(on current repo and so I can see output) and this is resoult:
*** Error in `/usr/bin/python': double free or corruption (fasttop): 0x00007f689001fa40 ***
All that I have found on this error is concerning music players(writen in python) and it is some memory issue -> http://goo.gl/RRFzu6 .
But in terminal command is not terminated, it still runs, maybe like orphan or zombie process, but still runs, so my ctrl+c of current operation(rabbitvcs commit) probably locks repo.

**Comment by CloCkWeRX** [comment]
I recommend you report that to an Ubuntu bug tracker - something similar to https://bugs.launchpad.net/ubuntu/+source/reportbug/+bug/536786
