### ISSUE TITLE
RabbitVCS Nautilus extension is not working at all on OpenSUSE 13.2

### ISSUE THREAD

**Issue by tuxtard** [rabbitvcs/rabbitvcs#88]
RabbitVCS Nautilus extension is not working at all on OpenSUSE 13.2. Tried: 
1. RPM version 0.15.0.5-1.42
2. 0.16 release from source
3. newest git version from source

There are no errors when I run nautilus from the shell.

**Comment by CloCkWeRX** [comment]
Need a bit more debugging information to go on - see what your xession-errors.log or rabbitvcs.log say.

**Comment by tuxtard** [comment]
Hi,

.config/rabbitvcs/RabbitVCS.log and xsession-errors are both empty.

**Comment by tuxtard** [comment]
I was able to get it working. It seems that OpenSuSE package wasn't updated to Gnome 3 and was still using Gnome 2 code. After manual cleanup of OpenSuSE packages and by manually downloading and adding RabbitVCS.py from here:

https://raw.githubusercontent.com/rabbitvcs/rabbitvcs/master/clients/nautilus-3.0/RabbitVCS.py

into /usr/share/nautilus-python/extensions it now works.
